### ISSUE TITLE
Feature request: Allow properties to be obtained from objects that implement `ContainerInterface`

### ISSUE THREAD

**Issue by bnf** [TYPO3/Fluid#1001]
The `StandardVariableProvider` currently requires objects to either implement `ArrayAccess` or provide `get{PropertyName}` methods, in order to provide access to sub-properties or sub-objects:

https://github.com/TYPO3/Fluid/blob/8fa917338d5bada78a2a3e39ac694076cf723d27/src/Core/Variables/StandardVariableProvider.php#L113C1-L115C16

`ArrayAccess` has the drawback to require `offsetUnset` and `offsetSet` methods, which are kind of anti-patterns in readonly objects – therefore implementing providers often implement the as throwing no-ops, example:
https://github.com/TYPO3/typo3/blob/b69732357e0d30a8088d7bb4931ba57bdd47b738/typo3/sysext/core/Classes/Domain/Record.php#L121-L129

It would be cool if fluid could resolve properties by obtaining values via `get()` if the object impements `\Psr\Container\ContainerInterface`.

**Comment by s2b** [comment]
The patch has been merged and will be part of Fluid v4.
