### ISSUE TITLE
Can not use PHP enum for tag attribute value

### ISSUE THREAD

**Issue by o-ba** [TYPO3/Fluid#1006]
When using a PHP Enum as attribute value following exception is thrown:

`Error: Object of class Vendor\Site\SomeEnum could not be converted to string`

**Comment by mbrodala** [comment]
On that note: [PHP RFC: Auto-implement Stringable for string backed enums](https://wiki.php.net/rfc/auto-implement_stringable_for_string_backed_enums) (Status: Withdrawn)

**Comment by s2b** [comment]
Resolved with #1007
