### ISSUE TITLE
XSD schema generator missing / not working

### ISSUE THREAD

**Issue by jkphl** [TYPO3/Fluid#108]
The [advertised schema generator](https://github.com/TYPO3Fluid/Fluid/blob/master/doc/FLUID_VIEWHELPERS.md#viewhelper-schema) seems to not be part of the package anymore. Also, even when manually added ([namelesscoder/fluid-schema-generator](https://packagist.org/packages/namelesscoder/fluid-schema-generator)), it doesn't seem to work with the current sources.

Additionally, Packagist states that `namelesscoder/fluid-schema-generator` is abandoned and one should use `typo3fluid/schema-generator`, but a package if this name doesn't seem to exist.

As a short term solution: Is there a recent schema including the most important viewhelpers downloadable somewhere?

**Comment by helhum** [comment]
http://insight.helhum.io/post/130270697975/updated-fluid-schema-urls
http://insight.helhum.io/post/85031122475/xml-schema-auto-completion-in-phpstorm
Which means that XSD for TYPO3 is here (this exact URL also includes the VHs of this repo):
http://xsd.helhum.io/ns/typo3/cms-fluid/master/ViewHelpers

Schema generation is possible (currently only for TYPO3 extensions and Fluid with https://github.com/helhum/typo3_console

**Comment by jkphl** [comment]
@helhum Yeah, thanks, I read that posts earlier. In the meantime [I have been able to generate the schema](https://twitter.com/jkphl/status/738484583956680704) I needed. But still I think it is worth noting that the documentaiton of this repo tells people that schema generation is possible — which isn't. I feel you should either adapt the docs or fix the schema generator!?

**Comment by helhum** [comment]
>  I feel you should either adapt the docs or fix the schema generator!?

absolutely! that's why I only added some info to help out, but did not close this bug report :)

**Comment by NamelessCoder** [comment]
https://github.com/NamelessCoder/TYPO3.Fluid.SchemaGenerator works for standalone Fluid but until further notice it has to be cloned from that GitHub repository. The plan is to provide this as an official TYPO3 package since that functionality is now gone from the standalone package itself and this separate package invites to create other ways of generating documentation, for example as live docs.

Let's keep this issue open until a final decision is made about that generator; where it's going to live and what the final composer name will be. Until then for everyone reading, clone the linked repository and generate away :)

**Comment by NamelessCoder** [comment]
By the way @helhum since you're here anyway - what's your opinion about shipping the XSD as part of the Fluid repository and keep it updated along with API changes? That would make a nice link target, supporting versions in URL and such. We of course still need to provide the generator but as an added help, maybe?

**Comment by jkphl** [comment]
@helhum Appreciated! :)

**Comment by helhum** [comment]
> what's your opinion about shipping the XSD as part of the Fluid repository and keep it updated along with API changes

I love the idea of having some automation in place to generate the XSD and I also like this idea to put it in a git repo. It feels strange however to pollute this repo here with that.

I'd rather have a github page repo (a branch might also be fine) with documentation only, where these things are pushed to on every commit by travis

**Comment by NamelessCoder** [comment]
> I love the idea of having some automation in place to generate the XSD

I may have the perfect middle way:

* A little hook listens for new tags
* When new tags are created it generates an XSD
* The hook talks back to GitHub and uses the API to attach a file to the release
* The file can be downloaded as part of the release, forever attached to all tags
* Can be generated and corrected "after the fact"

It looks like this when done:

https://github.com/NamelessCoder/rpc-client-osx/releases

And the link will contain the release number as such:

`https://github.com/NamelessCoder/rpc-client-osx/releases/download/1.0.0/TYPO3RPC-OSX-1.0.0.dmg`

But generally speaking about separating docs and source: I'm not sure I agree - it seems more appropriate that you get the docs associated with the version you clone/install. We can still use those assets to generate online documentation divided into versions, so essentially it is a matter of preference in terms of separation.

**Comment by helhum** [comment]
> I may have the perfect middle way
> The hook talks back to GitHub and uses the API to attach a file to the release

Sounds great!

> But generally speaking about separating docs and source: I'm not sure I agree - it seems more appropriate that you get the docs associated with the version you clone/install.

Oh, that is a misunderstanding. I of course like documentation to remain in the repo.
However what I dislike is the chicken-egg issue you face when auto generating stuff.

* For a release, I'd like to tag the current state in the repo.
* When a there is a release, I like to have docs generated.

How should the generated docs get into the tag? :)

**Comment by NamelessCoder** [comment]
> How should the generated docs get into the tag? :)

Assuming we put the docs as multiple MD/RST files, it seems best to commit them to the repository before tagging a new release. Doesn't really *solve* the chicken-and-egg issue but at least makes it clear that the egg (docs) must come before the chicken (release).

But perhaps we could deliver docs too via the release files we can attach using the GitHub API. Would work extremely well with XSD but not sure how well it would work with docs (we would, at the very least, have to restructure them so we can attach them as a single file or archive).

I think this one needs to simmer a while longer while we think about the docs perspective. And of course this issue itself needs to remain open until we've taken care of the XSD aspect.

**Comment by NamelessCoder** [comment]
Officially available as https://github.com/TYPO3/Fluid.SchemaGenerator (packagist registration is still pending).
