### ISSUE TITLE
CycleViewHelper doesn't work when static rendered

### ISSUE THREAD

**Issue by kitsunet** [TYPO3/Fluid#141]
The CycleViewHelper depends on a class property to store the current cycle it is rendering. This works when rendered initially but when rendered from a compiled state a new instance of the VH is created on every cycle effectively keeping the result stuck with the first cycle value.

Need to make up my mind how to solve that in a way that allows nesting as well...

**Comment by NamelessCoder** [comment]
You may want to read https://github.com/TYPO3Fluid/Fluid/pull/25 as inspiration here.

**Comment by kitsunet** [comment]
Perfect, will come up with a PR then!

**Comment by NamelessCoder** [comment]
Fixed a while ago :)
