### ISSUE TITLE
ElseViewHelper has an `if` argument that seems unused

### ISSUE THREAD

**Issue by kitsunet** [TYPO3/Fluid#155]
I thought at first that you could use else with a condition as `if` argument to get if/elseif/else behavior but I don't see any code actually implementing that. So either the argument definition is unnecessary or the implementation needs to be done?

**Comment by NamelessCoder** [comment]
This one is implemented in the "elseIfClosures" part - and the argument itself is used to create an "elseif" type node (an f:else that only gets rendered if the condition is true, and makes f:if continue checking next f:else nodes). Should definitely work!

**Comment by NamelessCoder** [comment]
Closing; hopefully the above explains it :)

**Comment by kitsunet** [comment]
Yep, didn't come around trying this out yet, but explanation is fine, thanks!
