### ISSUE TITLE
Variable name cut off

### ISSUE THREAD

**Issue by kitsunet** [TYPO3/Fluid#190]
Given an array assigned to `templateVariables` that contains a key `user2`.
Now I do:

```
<f:alias map="{user: testVariables.user2, firstName: testVariables.user2.firstName}">
{user.lastName}, {firstName}
</f:alias>
```

this fails, `user.lastName` (and after debugging also `user`) is null inside the alias (the direct access to `testVariables.user2.lastName` works just fine). Looking at the compiled template the resulting variable access is:
`$array1['user'] = $renderingContext->getVariableProvider()->getByPath('testVariables.user', $array2);`

As you can see the path was cut off and the `2` is missing in the end.

Will try to deliver more debug details, but for now this seems to b a bug in parse/compile.

**Comment by NamelessCoder** [comment]
This could be due to the Pattern class containing an expression for unquoted variable expressions in array parts not detecting tailing numbers. There was a change recently that allowed keys to be prefixed with a number so that may be the cause (if so, that's my bad).

**Comment by kitsunet** [comment]
Yep, can confirm it's

`\TYPO3Fluid\Fluid\Core\Parser\Patterns::SPLIT_PATTERN_SHORTHANDSYNTAX_ARRAY_PARTS`

specifically this line:
`|(?P<VariableIdentifier>[a-zA-Z0-9\-_.]*[a-zA-Z]+)  # variable identifiers must contain letters (otherwise they are hardcoded numbers)`

**Comment by NamelessCoder** [comment]
Bingo! Adding `0-9` in the last group should do the trick without destroying any features :)

**Comment by kitsunet** [comment]
yep, tried the same, but wasn't sure yet if that is the optimal solution

**Comment by NamelessCoder** [comment]
If you try that and confirm that hardcoding unquoted numbers as array values still works that should confirm it is the right solution.

**Comment by kitsunet** [comment]
Yep, can confirm unquoted numbers as array values still work fine, so that

`{f:format.json(value: {foo: 2})}`

is correctly parsed and results in the expected json with 2 as number type.

**Comment by NamelessCoder** [comment]
Excellent! Feel free to create a PR for this one :)

**Comment by benjaminkott** [comment]
Hey, is there any progress on this topic? This is currently breaking the introduction package on TYPO3 8.x at some points, would be awesome if we could get that fixed.

**Comment by kitsunet** [comment]
If no one does before, I will probably have a PR ready by tomorrow

**Comment by kitsunet** [comment]
This was not so easy after all. The original idea broke variables starting with digits, but this change should do the trick :)
