### ISSUE TITLE
RawViewHelper doesn't use `value` argument

### ISSUE THREAD

**Issue by kitsunet** [TYPO3/Fluid#209]
The `\TYPO3Fluid\Fluid\ViewHelpers\Format\RawViewHelper` registers a value argument to be used instead of the children but in fact never uses it in renderStatic nor in the compiled version, leading to NULL results in case the VH was used with the value argument eg.

`<f:format.raw value="don't encode" />`

**Comment by helhum** [comment]
This was introduced with #113 

The fix should include tests for this as weil

**Comment by NamelessCoder** [comment]
When using the CompileWithContentArgumentAndRenderStatic trait the *Closure* that renderStatic receives is where the decision is made to use the content argument or the original renderChildren closure that was built. Therefore the argument will never explicitly be consumed in the renderStatic method - but in your compiled template you definitely should see a ternary condition being built which generates a different closure if the content argument is set (`value` in this case; name is not required to be anything, the FIRST optional argument is always used).

**Comment by kitsunet** [comment]
Well, I see that a render children closure is build that returns null and this is just called and returned.
I have a test case here that exposes the problem.
Note that the RawViewHelper overwrites the `renderStatic` method which is probably why the trait doesn't have an effect.

**Comment by kitsunet** [comment]
Yes, that was a good info, removing the `renderStatic` method from the `RawViewHelper` fixes the problem.

**Comment by NamelessCoder** [comment]
I have something for this, hang on :)
