### ISSUE TITLE
[FEATURE] easier way to disable "{{" (and maybe also "{' for certain Javascript templates then CDATA per "{"

### ISSUE THREAD

**Issue by AndreasA** [TYPO3/Fluid#219]
I think it would be really nice to have an option to disable the "{{" support due to certain JavaScript templates without losing "{" support and not having to add CDATA per "{" that has such values.

For Javascript Code itself containing JSON disabling "{" would also be an idea.

Maybe in a way like disabling htmlspecialchars for certain code blocks that disables either "{{" or "{"

Probably not the highest priority though.

**Comment by kitsunet** [comment]
That would mean you need another language construct to make that happen. Ofc that could be a Viewhelper but it makes parsing a lot more complicated.
IMHO all parsing on or off is a solid way to work with this everyting else is overly complicated.

**Comment by AndreasA** [comment]
I think that would be enough too, I can just reenable the parsing for my fluid values then.
