### ISSUE TITLE
Add CLI for linting

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/Fluid#237]
It would be useful if there was a CLI command for linting Fluid templates. Given the nature of Fluid templates an XML linter cannot be used for this.

**Comment by NamelessCoder** [comment]
See https://github.com/NamelessCoder/TYPO3.Fluid.Lint and first five comments on https://github.com/TYPO3/Fluid/issues/108

**Comment by mbrodala** [comment]
I didn't notice that package. Could you release it on Packagist?

**Comment by NamelessCoder** [comment]
That's what the comments on #108 explains. TL;DR is I can't release extensions on the `typo3fluid` packagist vendor, I believe they belong in `TYPO3` on GitHub and in PHP Namespaces, and there is a relation to a potential renaming of `typo3fluid/fluid` on packagist to `typo3/fluid` (currently used by Flow) which would also probably affect the final names of these packages.

**Comment by NamelessCoder** [comment]
I would prefer `typo3/fluid-schema-generator` and `typo3/fluid-lint` - just in case you're able to create those. If you are, I will transfer those to `TYPO3` on GitHub and prepare pull requests to switch PHP namespaces.

**Comment by mbrodala** [comment]
I am not able to do this but I think you should raise this in the TYPO3 Slack. I see a lot of value if this is usable.

**Comment by NamelessCoder** [comment]
Available as https://github.com/TYPO3/Fluid.Lint (packagist release still pending).
