### ISSUE TITLE
Syntax check for boolean fluid expressions

### ISSUE THREAD

**Issue by cweiske** [TYPO3/Fluid#238]
## Problem
We have the problem that fluid simply ignores invalid syntax in templates and treats it as a string in case of syntax errors. for example, `<f:if condition="{settings.type === 'ordered'}">` is always true because there is the triple = instead of a double.
It gets even worse if you have complex objects.
Is there anything we can do to catch such errors?

## Chat discussion

> NamelessCoder:  cweiske there isn't much you can do for that specific use case. The reason is that passing any string value as condition is perfectly okay and results in TRUE unless the string is empty or contains a zero. So any invalid expression there silently gives a TRUE, and we can't make it not do that without completely breaking other use cases. We don't have a "this string looks like Fluid but isn't" check and such a check probably wouldn't be much good anyway.

> NamelessCoder:  if you move the expression out of the condition attribute that's still the best way to debug very complex boolean expressions

> NamelessCoder:  if the === issue is one you come across often we will of course consider adding that to the booleanparser capabilities

> NamelessCoder:  btw:  `<f:if condition="{settings.type === 'ordered'}">` should be  `<f:if condition="{settings.type} == 'ordered'">` so the === isn't the only thing in that expression (thus further proving your point)

> NamelessCoder:  let's ping @mneuhaus as well, maybe he has some way to make booleanparser throw up if for example it sees a purely hardcoded string that doesn't make sense as boolean expression... but I think it doesn't see any of that, only knows that it's a string but not where it came from, and we do not want to trigger this on strings coming from an object accessor node.

> cweiske: a linting tool would help, too. then we could use that in our commit hooks and on the test server

> mneuhaus:  we could to a "does this look like fluid syntax check" in cases where a boolean is expected i guess

> mneuhaus:  only usecase that could "blow up" is something like condition="{jsonData}" i guess

> mneuhaus:  if (is_string($booleanArgument) && looks_like_fluid($booleanArgument)) -> throw Exception

> mneuhaus:  it's an edgecase, but one we could adress i guess

> mneuhaus:  @NamelessCoder what do you think about that variant?

> NamelessCoder:  a linting tool would not detect this one cweiske because it is valid syntax to pass a string as condition

> NamelessCoder:  if the check is cheap I have no objection to that, I would advise though that it only happens in parsing, not once compiled

> NamelessCoder:  maybe in NodeConverter?

> NamelessCoder:  and... better throw an extreme amount of good test cases after that one to make sure it doesn't puke all over complex inline syntax!

> mneuhaus:  agreed, i guess we should be fine with a simple preg_match, that should be pretty cheap

> mneuhaus:  shouldn't interfere with that, imho

> NamelessCoder:  yeah I think so too, maybe even the existing preg from inline/shorthand syntax.

> mneuhaus:  because we'd be looking at it "after" the fluid logic

> mneuhaus:  kinda like, wtf, why did this fluid looking string slip through

> NamelessCoder:  I would check: 1) must be a TextNode input. 2) Must have zero child nodes. 3) must contain at least one occurrence of fluid syntax {.

> cweiske: { or }

> NamelessCoder:  oh, and another thing: consider having abstractcondition catch the error and output it in template instead of exception

> NamelessCoder:  condition vh already has access to parse-time arguments etc.

> NamelessCoder:  but afaics those checks would be pretty efficient to catch exactly this unintended string issue.

> NamelessCoder:  I will say it will have side effects though. Consider `<f:if condition="{inline:vh(arg: '{dontDoThis}') cdscdsc">`

> NamelessCoder:  resulting node structure is one root node containing three nodes; one text node, then an object accessor, then another text node

> mneuhaus:  @NamelessCoder we could hook in here instead

> mneuhaus:  https://github.com/TYPO3/Fluid/blob/master/src/Core/Parser/SyntaxTree/BooleanNode.php#L160

> mneuhaus:  that's after "all" parsing and evaluating is done

> mneuhaus:  we should take a hard look at the performance impact, but that could be the easiest and safest place to check for cases like this

> NamelessCoder:  then it also runs once compiled, that's what I wanted to avoid

> NamelessCoder:  hmm, the more I think about this the more I think it needs to happen in nodeconverter, delegated to booleanparser if needed but having access to the syntaxtree nodes that would be treated as boolean once parsed.

> NamelessCoder:  that's the only place we can be sure that some weirdo syntaxtree stack is an error, not something contained in for example TS variables, rte content, stupid markup etc.

----

Related:

- https://github.com/NamelessCoder/TYPO3.Fluid.Lint

**Comment by NamelessCoder** [comment]
https://github.com/NamelessCoder/TYPO3.Fluid.Lint/blob/master/src/FluidTemplateLinter.php#L107 might be a place to add syntaxtree-level checks, assuming the necessary node structure can be read (may require making internal Fluid API semi-public).

**Comment by lolli42** [comment]
Hey.

The problem that fluid tends to create a string from 'invalid syntax' is basically by design: the regex based parser basically triggers this. As such, this issue is very hard to fix when no new parser is used. We won't be able to change the behavior, and *if* a new parser strategy materializes, improved syntax detection would come as a side effect. We'll close here for now.
