### ISSUE TITLE
Performance regression due to additional `count` call

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3/Fluid#242]
Calling `count()` on an object can be very "expensive", especially if it's a `QueryResult`-object with a large set of records as a `SELECT COUNT(*)` can be very slow with a lot of records (pagination, i.e. a limit/offset won't make a difference).

In my case it's more than an order of a magnitude difference to render 30 records at once (0,042s vs 0,76s)

The bottleneck comes with the newly introduced [AbstractViewHelper::isValidType()](https://github.com/TYPO3/Fluid/blob/master/src/Core/ViewHelper/AbstractViewHelper.php#L355-L383):
It does some (possibly dangerous and expensive) operations on the given arguments, including `count` and `getFirstElementOfNonEmpty()` on collection values.

[Previously](https://github.com/neos/fluid/blob/master/Classes/TYPO3/Fluid/Core/ViewHelper/AbstractViewHelper.php#L483-L517) we only checked whether the type matched the argument definition

BTW: There's another possible side-effect in the argument validation: `getFirstElementOfNonEmpty()` actually resets any collection argument

**Comment by bwaidelich** [comment]
(reference: https://github.com/neos/flow-development-collection/issues/759)

**Comment by bwaidelich** [comment]
FYI: A quick fix is to replace
```php
} elseif (count($value) > 0 && substr($type, -2) === '[]') {
```
by
```php
} elseif (substr($type, -2) === '[]' && count($value) > 0) {
```
in `AbstractViewHelper::isValidType()`

Which makes sense anyways IMO - but obvously that's just a fix for _some_ of the cases

**Comment by NamelessCoder** [comment]
I'm thinking we may be able to drop the `count()` entirely in the case above. I'm looking into that right now.

**Comment by NamelessCoder** [comment]
https://github.com/TYPO3/Fluid/pull/245 could be a way to deal with the count() in argument validation. It does however slightly change the verdict for non-empty arrays/iterators where the first value is null, for whichever reason. Such cases are now considered valid (taken as reasonable indication that the subject was empty, thus valid).

**Comment by bwaidelich** [comment]
Great, I like!
