### ISSUE TITLE
Don't `count` objects in `ForViewHelper` if not required

### ISSUE THREAD

**Issue by bwaidelich** [TYPO3/Fluid#243]
When specifiying the `iteration` argument in the `f:for` ViewHelper some more details about the current iteration and the total number of items is determined.

[Previously](https://github.com/neos/fluid/blob/master/Classes/TYPO3/Fluid/ViewHelpers/ForViewHelper.php#L115-L121) this was only done if the argument was actually set.
[Now](https://github.com/TYPO3/Fluid/blob/master/src/ViewHelpers/ForViewHelper.php#L112-L116) these details are always calculated whether used or not leading to a severe performance regression (see #242)

**Comment by bwaidelich** [comment]
Reference https://github.com/neos/flow-development-collection/issues/760

**Comment by NamelessCoder** [comment]
Confirmed; we can implement a condition to only trigger this counting if `iteration` was specified!

**Comment by bwaidelich** [comment]
I already prepared a PR with test, unfortunately #242 still kicks in and makes the test fail

**Comment by NamelessCoder** [comment]
Version `2.1.1` is pushed and ready to use! Thanks for reporting these :)

**Comment by bwaidelich** [comment]
man, you're fast ;)

**Comment by NamelessCoder** [comment]
We aim to please ;)

**Comment by kitsunet** [comment]
Btw. how is the backporting policy?

**Comment by NamelessCoder** [comment]
> Btw. how is the backporting policy?

We still backport bug fixes (respecting semantic versioning) but not with as high priority as releases on the current branch.

We do this by:

* Checking out whichever branch we backport to.
* Creating a new PR branch from it.
* Cherry-picking all wanted backports.
* Pushing the PR branch to personal fork and opening the pull request, causing the commits to be tested by CI.
* But *not* merging the pull request branch; instead, we push the picked commits directly to the target branch (which then causes the pull request to close itself automatically).
* Tagging and pushing a new release on the branch we pushed to.

Let me know if you require backports to 1.0, 1.1 or 2.0 branches, I don't mind taking care of those!

**Comment by kitsunet** [comment]
Goes a bit beyond this but.... We are currently on 2.0.x, I wouldn't mind moving to 2.1.x but we are very shortly before release so I am not sure if that is still happening... So 2.0 would be much appreciated :)

**Comment by kitsunet** [comment]
ok nevermind I trusted semver and required "^2.0.4", so we get 2.1.x versions anyway.
