### ISSUE TITLE
Viewhelper arguments are not casted to their expected type

### ISSUE THREAD

**Issue by sascha-egerer** [TYPO3/Fluid#253]
If a argument is registered with a type like `bool` the value will not be casted to that type if defined in the template.

Example:
```
$this->registerArgument('absolute', 'bool', 'If set, an absolute URI is rendered', false, false);
```

If you use the viewhelper with this argument
```
<f:foo absolute="true" />
```
You'll get a string containing `true` but not a boolean representation.

You can reproduce that with the TYPO3 CMS `f:uri.action` viewhelper (https://github.com/TYPO3/TYPO3.CMS/blob/f73029e/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ActionViewHelper.php#L54). In the `f:link.action` viewhelper (https://github.com/TYPO3/TYPO3.CMS/blob/f73029e/typo3/sysext/fluid/Classes/ViewHelpers/Link/ActionViewHelper.php#L66) the value is casted correct as is registered as an annotated argument in the `render` function and not via `registerArgument`. So the conversion is already done at another place but should be done by fluid.

**Comment by mneuhaus** [comment]
Hey Sascha,

you're right, there seems to be a problem regarding the usage of "bool" instead of "boolean".
i think i've located the issue and will push a pull-request tomorrow.

Cheers
Marc

**Comment by mneuhaus** [comment]
Hey Sascha,

could you test if #254 fixes the issue for you?
