### ISSUE TITLE
Refactor condition ViewHelper logic

### ISSUE THREAD

**Issue by NamelessCoder** [TYPO3/Fluid#257]
The following refactoring is suggested:

1. Move render() method from IfViewHelper to AbstractConditionViewHelper.
2. Declare evaluateCondition abstract on AbstractConditionViewHelper, requiring implementations to implement the method.
3. Move "condition" argument from AbstractConditionViewHelper to IfViewHelper.
4. Change method signature for evaluateCondition to require an array and not allow null values.

**All of the above points would constitute breaking changes.**

The result is that condition ViewHelpers can be written by simply subclassing AbstractConditionViewHelper, implementing evaluateCondition and finally (if needed by evaluateCondition method) override initializeArguments, call parent::initializeArguments to gain "then" and "else" argument support, then add whichever argument the specific condition ViewHelper requires (in the case of IfViewHelper, that means the "condition" argument). If a ViewHelper requires no additional arguments as input, only the evaluateCondition method is needed (example: conditions which check hardcode-named environment variables).

The benefit will be that condition ViewHelpers get a streamlined interface that is strict enough to ensure operability, but loose enough to let third party condition ViewHelpers safely use parent's arguments for "then" and "else" and add any named argument it wants, to determine true/false evaluation.

This will also prevent frameworks from being able to use render() method arguments on any condition ViewHelper; but arguments registered in initializeArguments will of course still work.

Example implementation after conversion (complete class):

```php
class IfViewHelper extends AbstractConditionViewHelper
{

    /**
     * Initializes the "then" and "else" arguments
     */
    public function initializeArguments()
    {
        parent::initializeArguments();
        $this->registerArgument('condition', 'boolean', 'Condition expression conforming to Fluid boolean rules', false, false);
    }

    /**
     * Simplest of all possible evaluations - returns true if the
     * boolean argument in "condition" is true.
     *
     * @param array|NULL $arguments
     * @return boolean
     * @api
     */
    protected static function evaluateCondition($arguments = null)
    {
        return (boolean) $arguments['condition'];
    }
}
```

Example abstract condition ViewHelper class (partial class):

```php
abstract class AbstractConditionViewHelper extends AbstractViewHelper
{

    /**
     * @var boolean
     */
    protected $escapeOutput = false;

    /**
     * Initializes the "then" and "else" arguments
     */
    public function initializeArguments()
    {
        $this->registerArgument('then', 'mixed', 'Value to be returned if the condition if met.', false);
        $this->registerArgument('else', 'mixed', 'Value to be returned if the condition if not met.', false);
    }

    /**
     * @param array $arguments
     * @return boolean
     * @api
     */
    abstract protected static function evaluateCondition(array $arguments);

    /**
     * Renders <f:then> child if condition is true, otherwise renders <f:else> child.
     *
     * @return string the rendered string
     */
    public function render()
    {
        if (static::evaluateCondition($this->arguments)) {
            return $this->renderThenChild();
        } else {
            return $this->renderElseChild();
        }
    }

    // ... rest of class body
}
```

Comments / alternatives welcome!

**Comment by NamelessCoder** [comment]
Pinging @kitsunet, @mneuhaus, @bmack - we would like to include this one in Fluid 3.0 which is already expected to contain some breaking changes. At the current time, the following implementations are known:

* Fluid's IfViewHelper (continues working unaffected).
* TYPO3 implementations (5 total; one of which is a custom AbstractConditionViewHelper).
* Neos/Flow's implementations of the same ones TYPO3 carries.
* VHS's semi-large collection of conditions (can be handled with dependencies; if Fluid 3.0 is not added until next TYPO3 LTS then VHS will simply bump to that requirement).
* Fluid/Extbase helpers from @4eyes (appears discontinued, pinging @MichelGeorgy for good measure)
* Parts of EXT:news (pinging @georgringer for good measure)
* Parts of EXT:powermail (pinging @einpraegsam for good measure)

All of you are of course invited to give your feedback :)

**Comment by DanielSiepmann** [comment]
Does that relate, at least on some way, to #273?
So can we tackle this bug while refactoring?

**Comment by NamelessCoder** [comment]
No longer required, see https://github.com/TYPO3/Fluid/pull/393.
