### ISSUE TITLE
iteration.islast not working for Iterator implementors

### ISSUE THREAD

**Issue by useltmann** [TYPO3/Fluid#267]
the `iteration.isLast` condition is not working for non-ArrayIterators. after the first iteration it is always returning `true` since `count(IteratorObj)` is always `1`

**Comment by useltmann** [comment]
i withdraw this issue. its easier to implement the `Countable` interface

**Comment by NamelessCoder** [comment]
You beat me to it with that suggestion, `Countable` is the explicit way ;)

Side note: if you come across a similar case in the future make sure you check if the input is an array and use `count()` if it is. Sadly, the iterator counting function doesn't support arrays.
