### ISSUE TITLE
AbstractTagBasedViewHelper: add ignoreEmptyAttributes

### ISSUE THREAD

**Issue by cweiske** [TYPO3/Fluid#275]
It should be possible to remove empty tag attributes that have been listed in `additionalAttributes`, e.g. with a new attribute `ignoreEmptyAttributes`.

See https://github.com/FluidTYPO3/vhs/issues/1125 for more information.

**Comment by cweiske** [comment]
Solved by https://github.com/TYPO3/Fluid/pull/302

**Comment by NamelessCoder** [comment]
Thanks for the followup, @cweiske - I forgot to connect the PR with this issue.
