### ISSUE TITLE
Is the documentation up to date?

### ISSUE THREAD

**Issue by MajPay** [TYPO3/Fluid#276]
I cant figure out how to generate the schema for my ide, is this documentation still up to date?
https://github.com/TYPO3/Fluid/blob/HEAD/doc/FLUID_VIEWHELPERS.md#viewhelper-schema

**Comment by lolli42** [comment]
Hey. I hope it's ok to close here for now: The referenced link does not work anymore and quite a bit happened on docs with younger versions meanwhile. Please create a fresh issue if there is still some confusion.
