### ISSUE TITLE
Foreign namespace declaration builds broken proxy templates

### ISSUE THREAD

**Issue by zdreicom** [TYPO3/Fluid#282]
e.g.

if i use svg image in templates like:

    <f:layout name="Default"/>
    <f:section name="main">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 400 160" style="enable-background:new 0 0 400 160;" xml:space="preserve">
                <style type="text/css">
   ...........

will create an  proxy output like this:

    public function addCompiledNamespaces(\TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface $renderingContext) {
    $renderingContext->getViewHelperResolver()->addNamespaces(array (
      'core' => 
      array (
        0 => 'TYPO3\\CMS\\Core\\ViewHelpers',
      ),
      'f' => 
      array (
        0 => 'TYPO3Fluid\\Fluid\\ViewHelpers',
        1 => 'TYPO3\\CMS\\Fluid\\ViewHelpers',
      ),
      'formvh' => 
      array (
        0 => 'TYPO3\\CMS\\Form\\ViewHelpers',
      ),
      'xlink' => null // -> Foreign namespace
    ));
    }

this will result in an error:

     1476107295: PHP Warning: in_array() expects parameter 2 to be array, null given in .../typo3_src-8.7.1/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperResolver.php line 92

**Comment by NamelessCoder** [comment]
@zdreicom thanks for reporting! If you could confirm #283 on TYPO3 CMS that would be great :)

**Comment by EnzephaloN** [comment]
I think I ran into this using TYPO3 8.7.2.
There is a template with that code `<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom">`
And I get this error:
```
PHP Warning: in_array() expects parameter 2 to be array, null given in /home/www/typo3_src/typo3_src-8.7.2/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperResolver.php
...
24 TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperResolver::addNamespace("content", NULL)
...
```
I applied the patch ec2d710 and the error is gone! Great work! Hope this will be merged soon!

**Comment by opi99** [comment]
Run in same issue and applying patch from #283 fixed it
