### ISSUE TITLE
The ìf' argument in an "elseif"-like behavior is ignored when no `else` without an ìf` argument exists

### ISSUE THREAD

**Issue by jdreesen** [TYPO3/Fluid#284]
I just created a construct like this in my template
```html
<f:if condition="{condition_1}">
	<f:then>
		...
	</f:then>
	<f:else if="{condition_2}">
		...
	</f:else>
</f:if>
```
and expected that nothing would be output if `condition_1` and `condition_2` both evaluate to false but the contents of `<f:else if="{condition_2}">` were printed. I had to add an extra `<f:else>` (without an `if` argument) to prevent the contents of the `elseif` from being printed.

This seems to be a bug as I don't think that this is the desired behaviour.

**Comment by NamelessCoder** [comment]
If the second condition is false then it's absolutely not the intended behavior. The problem could lie somewhere in the code that identifies either the first matching `else` condition, or the first encountered `else` which has no condition. We'll look into that (if you don't beat us to it).

**Comment by jdreesen** [comment]
I gave it a try in #289.
