### ISSUE TITLE
Variable extractor should be able to use `has$propertyName()`

### ISSUE THREAD

**Issue by cedricziel** [TYPO3/Fluid#286]
Given a variable with the following class:

```
class Cake
{
  protected $glitter;

  public function hasGlitter () {
    return $this->glitter;
  }
}
```

As of today, the extractor wouldn't be able to extract the value out of the expression `{foo.glitter}`.

The Variable extractor should be able to use methods like `has$Property` like it does handle `is$property`, so they can be used interchangeably.

**Comment by NamelessCoder** [comment]
Change would be welcome. If you do create a PR, please wrap the additional method call/check into the condition which uses the "asserter" constant and make the "hasFoobar" call/check the second priority after the "isFoobar" one.

**Comment by cedricziel** [comment]
Before I open another issue - I think magic methods should be supported as well - today that's not possible, but `symfony/property-access` (think a battle tested `VariableExtractor` on steroids) supports it as well.

What do you think?

**Comment by NamelessCoder** [comment]
I will take a property access replacement into consideration. If other spare parts you've seen lying around will apply to Fluid do mention those as well - if we *are* going to adopt our first dependency, we may as well look into which others might make sense ;)

Thanks for the patch btw!
