### ISSUE TITLE
Latest version (v2.3.4) is not on packagist

### ISSUE THREAD

**Issue by jdreesen** [TYPO3/Fluid#297]
Somehow the [latest tagged version](https://github.com/TYPO3/Fluid/releases/tag/2.3.4) doesn't appear on packagist. It says the latest version is still v2.3.3: https://packagist.org/packages/typo3fluid/fluid

**Comment by NamelessCoder** [comment]
I've manually refreshed Packagist to include 2.3.4.

Ping @bmack or someone else who has permission to read the API token on Packagist and insert it into the settings here in the repository.

**Comment by bmack** [comment]
Hey,

just updated the hook again. Should be fine now on next push/release

**Comment by jdreesen** [comment]
Thx! :)
