### ISSUE TITLE
Spaceless ViewHelper removes too many spaces

### ISSUE THREAD

**Issue by nitori** [TYPO3/Fluid#298]
The Spaceless ViewHelper makes the assumption, that all whitespaces between a closing (`>`) and opening (`<`) HTML tag marker (if there are only whitespaces) can be removed.

This is especially troublesome, if you have markup with two consecutive inline elements, for example:

```
Lorem ipsum dolor sit amet, <em>consectetuer</em> <strong>adipiscing</strong> elit.
```
This, unexpectedly, removes the space(s) between closing `</em>` and opening `<strong>` and causes those words to stick together when they shouldn't.

This problem can be observed in TYPO3 8 with the new RTE, when the text is styled as shown above.

I would suggest that the spaces should be removed down to one single space, if there is at least one whitespace between `>` and `<`.

**Comment by mbrodala** [comment]
Notice that the viewhelper is called _spaceless_, thus it does what it should.

If you simply want to reduce multiple whitespace characters to a single one, you should add your own viewhelper which does exactly that.

Anything more sophisticated would require a full-fledged HTML parser which understands the concept of block and inline elements as well as flow content.

**Comment by nitori** [comment]
But then doesn't that mean the ViewHelper is used incorrectly in TYPO3 fluid_styled_content? Currently I *always* have to overwrite the [default layout](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid_styled_content/Resources/Private/Layouts/Default.html) of FSC to get rid of that "feature" (which is clearly a bug and should not be).

I opened an [issue on forge](https://forge.typo3.org/issues/80695), but it was rejected without reason.

**Comment by mbrodala** [comment]
I guess @georgringer could answer here.

**Comment by DanielRuf** [comment]
I also see no bug with this helper. Maybe add an optional parameter to just collapse multiple spaces to one or create a separate helper makes sense.

**Comment by NamelessCoder** [comment]
An argument to toggle this behavior would make more sense than changing the default behavior. The one thing we can't support without making the spaceless ViewHelper *very* complex, is to nest `f:spaceless` and expect the nested one to behave differently - it will always be the outermost instance that decides how the trimming happens. Just to warn you in advance that even a toggle for the behavior isn't a golden bullet!

**Comment by DanielRuf** [comment]
According to the comments it should behave like the spaceless helper of Twig.

https://twig.sensiolabs.org/doc/2.x/tags/spaceless.html

I guess it is generally not the usecase of this helper to remove whitespaces from combined and nested elements but to flatten beautified code snippets.

Should this helper still follow the rules of the spaceless helper in Twig, should we extend it with a parameter or should we introduce/create a new helper (if it does not yet exist) to collapse/compress spaces (or another optional character supplied as parameter)?

What do you think?

**Comment by nitori** [comment]
I'm perfectly fine with not changing anything with the ViewHelper, but I think it should the be removed from the fluid_style_content default layout file (I have to override it every time). Spaceless does not fullfill the role of minifying the html output, without affecting the browser rendered output. It might be usable in some places like pure XML, that does not know the notion of inline/block elements, or in cases where the developer knows that no side effects are going to appear.

The job of minifying HTML properly should be left to extensions instead.

**Comment by NamelessCoder** [comment]
I would personally agree that we shouldn't make such decisions for all users (I see f:spaceless as purely opt-in and something to use when you know the HTML can tolerate it). But that's an issue to report to TYPO3 CMS because we can't change that from this library.

**Comment by bmack** [comment]
I think an additional parameter would be really useful $preserveWhitespacesBetweenTags - as I see a need for both use-cases in projects.

**Comment by NamelessCoder** [comment]
I have no objection to a new argument for f:spaceless, as long as the default behavior is the current one.

**Comment by lolli42** [comment]
Closing issue in favor of #154

**Comment by liayn** [comment]
TYPO3 specific bug report: https://forge.typo3.org/issues/86862
