### ISSUE TITLE
Non-zero value evaluates to FALSE in condition of <f:if> viewhelper

### ISSUE THREAD

**Issue by stoppeye** [TYPO3/Fluid#301]
Testing for a non-zero value in Fluid 8.7.0 doesn't evaluate as TRUE as it used to in 6.2.0 (or PHP in general):

    <f:if condition="-1">
    TEST
    </f:if>

This doesn't print TEST. It seems that only positive non-zero values will test TRUE.

**Comment by DanielRuf** [comment]
Event the docs are not right:
https://docs.typo3.org/typo3cms/ExtbaseFluidBook/8-Fluid/7-using-boolean-conditions.html

> A number for example is evaluated as true if it is greater than 0.

See http://php.net/manual/en/language.types.boolean.php
> Warning
-1 is considered TRUE, like any other non-zero (whether negative or positive) number!

https://softwareengineering.stackexchange.com/a/300792/41772

**Comment by stoppeye** [comment]
Ich bin zur Zeit abwesend und ab dem 3.7. wieder erreichbar. Ihre Mails werden nicht weitergeleitet. Bei dringenden Nachfragen wenden Sie sich bitte an info[at]eye.ch oder telefonisch an 061 416 91 81.

Mit freundlichen Grüssen
Michael Stopp
