### ISSUE TITLE
LayoutPathAndFilename not used after set

### ISSUE THREAD

**Issue by dj-rabel** [TYPO3/Fluid#309]
Hello,

i just experienced that a expecially set layoutPathAndFilename will never be returned from the getLayoutPathAndFilename method in \TYPO3Fluid\Fluid\View\TemplatePaths

See https://github.com/TYPO3/Fluid/blob/c9f9df06579a351650736c34a87588a1fef292e8/src/View/TemplatePaths.php#L633

It is mentioned in the Docblock Comment but is never returned ...

I've added the following lines to fix this:
```
if ($this->layoutPathAndFilename !== null) {
    return $this->layoutPathAndFilename;
}
```

I would also suggest to change the line https://github.com/TYPO3/Fluid/blob/c9f9df06579a351650736c34a87588a1fef292e8/src/View/TemplatePaths.php#L150 so sanitize the layout path as well
`$this->layoutPathAndFilename = (string) $this->sanitizePath($layoutPathAndFilename);`

And as last, I mentioned that theres no method to set the layoutPathAndFilename in the TYPO3\CMS\Fluid\View\StandaloneView.

greets
Ruben

**Comment by NamelessCoder** [comment]
Sounds like the right way to patch this one (and I agree it should be supported, must have been unintentionally left out during the refactoring - it's a very rarely used feature). You are very welcome to open a pull request with the change exactly as suggested ;)

**Comment by dj-rabel** [comment]
> You are very welcome to open a pull request with the change exactly as suggested ;)
With pleasure
