### ISSUE TITLE
possible performance improvements

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3/Fluid#317]
I'm not 100% sure but I might have found some codeparts which can be improved to gain more performance.

https://github.com/TYPO3/Fluid/blob/617595f736ca1e880817cea852572b9b0b329f39/bin/fluid#L260-L262
https://3v4l.org/rtCMQ

Probably found some other parts too but I have to create more realistic tests for them.

Probably more candidates:
https://github.com/TYPO3/Fluid/blob/c9f9df06579a351650736c34a87588a1fef292e8/src/View/TemplatePaths.php#L704-L718

https://github.com/TYPO3/Fluid/blob/6186eeb3547c137881329d81ed9e67c094350c6d/src/Core/ViewHelper/ViewHelperResolver.php#L326-L328

And maybe some switch / case statements (can be replaced with if / elseif using ===).

Opinions about this are very welcome (if it makes sense to improve these and other parts or not).

**Comment by DanielRuf** [comment]
Bump.

**Comment by mbrodala** [comment]
If you feel you found places which can be speed up without sacrificing too much readability go ahead and make a PR. If possible also check if the place you are changing is covered by tests properly to avoid regressions.
