### ISSUE TITLE
Support "and" in addition to "&&" in boolen expressions

### ISSUE THREAD

**Issue by cweiske** [TYPO3/Fluid#319]
The boolean expression parser only allows `&&` for AND conditions - https://github.com/TYPO3/Fluid/blob/master/src/Core/Parser/BooleanParser.php#L202

When using `&&` in attribute values, the resulting files are not well-formed anymore because in XHTML each `&` must either start an entity, or be escaped as `&amp;`.

A solution would be to add `and` as a synonym for `&&`, which would allow us to write well-formed HTML templates that can be validated with `xmllint`.

**Comment by NamelessCoder** [comment]
Good point about the XML validity, I did not consider that one. @mneuhaus what do you think - any blockers preventing us from allowing case insensitive `and` / `or` in the boolean expression?

**Comment by mneuhaus** [comment]
No harm in throwing it in and see what the unit tests say, they are quite extensive :+1:
my gut feeling is that it shouldn't be a problem :)

**Comment by bmack** [comment]
+1
