### ISSUE TITLE
Variable assignment with f:variable in compiled templates may fail

### ISSUE THREAD

**Issue by NamelessCoder** [TYPO3/Fluid#334]
Presented use case:

```xml
<f:variable name="zero1" value="0" />
{f:variable(name: 'zero2', value: 0)}
<f:debug>{zero1}</f:debug>
<f:debug>{zero2}</f:debug>
```

When I first call this, the output is:

0 (integer)
0 (double)

After simply reloading the browser, the output becomes:

NULL
NULL

-------------------------------------------------------

Assuming the above is true, f:variable may have a problem assigning the variable once the template is compiled; or the variable provider somehow does not return the right variable.

**Comment by X-Tender** [comment]
I've stumbled over this issue too.
is there a bugfix around or a patch?

**Comment by maikschneider** [comment]
Not sure if this is the fix: https://github.com/TYPO3/Fluid/pull/333
The problem is still present in current TYPO3 v8.7.8.

**Comment by lolli42** [comment]
this was fixed meanwhile, we're adding a test case to show this.
