### ISSUE TITLE
process data-src for lazysizes

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3/Fluid#345]
To support https://github.com/aFarkas/lazysizes and other solutions for lazyloading / deferring images we need data-src instead of data.

https://varvy.com/pagespeed/defer-images.html

So far `data-src` does not work as `src` is required and `data-src` throws `You must either specify a string src or a File object.`.

Even in VHS and its image view helpers.

What is the recommended way to go here and also support picture tags with this approach?

**Comment by sascha-egerer** [comment]
I would say the current way is the recommend one and it is also correct.
Images without a src attribute are not valid in HTML so it should always be there.
It should be possible to add a data-src as you can add everything prefixed with `data-`.
For the source attribute you could use a placeholder image.

**Comment by DanielRuf** [comment]
This would not work with the PictureViewHelper as it uses the `src` for the creation of the different variants.

https://fluidtypo3.org/viewhelpers/vhs/master/Media/PictureViewHelper.html

**Comment by DanielRuf** [comment]
A placeholder image is not the solution when working with optimized images using cropping, srcset / source and so on.

**Comment by sascha-egerer** [comment]
The viewhelper you've linked is not part of fluid. Are you just talking about that one? Then i will close the issue here.

**Comment by DanielRuf** [comment]
The issue is meant for fluid and vhs viewhelpers where we need the cropped / processed image in data-src instead of src. I'll create a separate issue for vhs.

**Comment by DanielRuf** [comment]
> Even in VHS and its image view helpers.

**Comment by sascha-egerer** [comment]
Lets wait for feedback from @NamelessCoder as there are plans to change those argument handling anyway. Maybe thats also relevant here.

**Comment by NamelessCoder** [comment]
Fluid itself has no image rendering so this is definitely not an issue for Fluid itself. Arguments can be used any way you prefer and in this case, it's an issue of a base class registering required arguments and setting a specific attribute on the resulting tag.

We can consider such changes in the repositories that implement image handling, e.g. VHS or TYPO3. Note that VHS subclasses the TYPO3 image ViewHelpers so the right place to suggest this would be in TYPO3, which would give VHS the capability automatically.

**Comment by DanielRuf** [comment]
Ok, that makes sense.

Where should I open an issue for this and can I describe this better?

**Comment by DanielRuf** [comment]
Generally we would have to map `src` to `data-src` also for processed / cropped images and generate a pseudo `src` directly in Fluid templates or on another way.

I would welcome to see a image lazyloading solution in the core, Fluid or VHS.

**Comment by sascha-egerer** [comment]
I think you won't get this as default behavior. `data-src` attributes are custom attributes. If you're using a JS that does it like that you should also use a custom viewhelper that does it like you need it. 
I would suggest to write a hook that manipulates the attributes for your needs. 
But sadly there is currently no hook / signal to manipluate arguemnts. Maybe that would be a first step

**Comment by NamelessCoder** [comment]
https://forge.typo3.org/projects/typo3cms-core/issues seems like the place to report this - but I'm sure there are existing issues that deal with this so please check before you open a new one.

Don't forget that an equally valid way to deal with this is to generate the resource URI and construct your `img` or `picture` or whichever tags manually, using the generated URI in any attribute you like, and leaving out any attributes that are normally required due to ViewHelper argument registrations.

**Comment by sascha-egerer** [comment]
@NamelessCoder But if you do that you'll not have valid width and height values in your tag which could be a problem with flipping content if there is no hard aspect ratio defined by a parent container

**Comment by NamelessCoder** [comment]
The challenges re: aspect ratio, retina versions, lazy loading and such must all be solved with either ViewHelpers or ViewHelper arguments. Although this isn't exactly the place to discuss that, I will say that in the case of both image sizes and aspect ratios it would be possible to create a ViewHelper that reads these properties from the resized image URI you get from URI-generating ViewHelpers. Also, the target widths and/or aspect ratios *really* should be either hardcoded in templates or passed as variables, in which case, you'd have those values available right away.

This is indeed a much deeper discussion related to template writing strategies in the use case of responsive and lazy-loading images, but from the perspective of Fluid itself, this is 100% up to the implementation and Fluid won't likely ever include any image-resizing ViewHelpers.

**Comment by NamelessCoder** [comment]
> But sadly there is currently no hook / signal to manipluate arguemnts. Maybe that would be a first step

I've been slowly working on an event and event data integration that will serve as hooks. This is not completed and would introduce the first ever dependency in the repository - but it would allow arguments and attributes to be manipulated with hooks.

That said, this case really calls for a custom ViewHelper (or changes to the ViewHelper from TYPO3) since you'd also need to override other aspects such as the tags being generated. Hooks/signals would *not* be an efficient way to achieve that!

**Comment by DanielRuf** [comment]
Is there generally a way to just generate the image URL (of the cropped / processed image) in Fluid using the ViewHelpers? This could be a solution.

**Comment by NamelessCoder** [comment]
In terms of TYPO3 CMS, `f:uri.image` has scaling and copping features like the tag-based variant. The output from this can then be used in other ViewHelpers to read size (but chances are you already know the size if you resize the image in Fluid; you'd need to pass the arguments in the first place).

**Comment by DanielRuf** [comment]
Ah, then this would solve my issue. I guess we can use the `f:uri.image` approach and render a picture partial with the needed inline Fluid ViewHelpers. I guess I can close the other issue too?

Probably I could present how we would solve this so other frontend teams would have some modern approaches for this specific use case.

**Comment by NamelessCoder** [comment]
If you're into the whole atomic design thing, it would absolutely be a good idea to create an image partial that has specific arguments and perhaps even basic sanity checks in the form of conditions + `f:variable` that can assign default values if arguments aren't passed (hint: `f:or` is designed for this).

I think you can close the other issues and work around this in an acceptable fashion without needing patches, but your suggestion to expand the tag-generating image ViewHelper in TYPO3 shouldn't be forgotten so I encourage you to check/open an issue for their bug tracker ;)
