### ISSUE TITLE
Viewhelper to stop fluid engine

### ISSUE THREAD

**Issue by jmverges** [TYPO3/Fluid#346]
Hi there,

is there any ViewHelper I'm missing to be able to stop fluid from parsing itself? I'm using Fluid with Vue.js inline-template options and {{whatEverVue.Value}} is tried to be resolved by fluid. I tried with 

```                        
<![CDATA[
                        {{whatEverVue.Value}}
]]>
```
and 

```
<f:format.raw>{{whatEverVue.Value}} </f:format.raw>
```

but I'm getting same result.

f:stopEngine f:dontParse...

**Comment by sascha-egerer** [comment]
you can use `{parsing off}`

https://github.com/TYPO3/Fluid/blob/412e04a70ad12cd14a8923a3b9b130dd3e68dc48/examples/Resources/Private/Singles/Passthrough.html#L1-L5

This will disable fluid for the whole file. So you can put all you stuff into a partial and disable fluid rendering there.

Or you just change the delimiter in vue.js.

**Comment by jmverges** [comment]
Awesome, thank you

**Comment by tantegerda1** [comment]
Just to get that right: The `<![CDATA[` / `]]>` functionality is no longer available?

**Comment by NamelessCoder** [comment]
CDATA is still available (also as f:format.cdata).

**Comment by fritzdacat** [comment]
Have the same problem: <! [CDATA []]> is no longer with me, if I make a <f: format.cdata> {{name}} </ f: format.cdata>, the source code is <! [ CDATA []]> TYPO3 8.7.8

**Comment by jmverges** [comment]
@fritzdacat {{ name }} putting spaces will solve your issue

**Comment by fritzdacat** [comment]
does not work for me, then I get the following error message:

Error: Parse error on line 3:
{{ #if data.logo }}

**Comment by fritzdacat** [comment]
ok, great! if I do not empty it on {{#if data.logo}}, it works

**Comment by mkrappitz** [comment]
FYI: {{something}} does not stop the fluid parser to throw exceptions for unresolvable namepsaces in viewhelpers. This was an issue for me rending an rss feed with fluid containing such tags: <media:content xmlns:media="..." url="..." medium="image" type="image/jpeg" /> where i just want them to output media:content and not to look for a media: viewhelper namespace. In TYPO3 7 this was no issue as there this was just outputted when the namespace could not be resolved. Also in TYPO3 7 you could <![CDATA[ / ]]> to disable parsing in parts of the template, which i unfortunately used intensively in one project.  There also {{ }} does not help as a replacement. So to solve my namespace issue described above I used a string replace viewhelper to do {e:stringReplace(string : 'media_content', searchFor : '_', replaceWith : ':')}, then the fluid parser stops caring about the not resolvable media: namespace. Hacky solution. Any better ways to achieve this?
