### ISSUE TITLE
[QUESTION / BUG?] using the trait CompileWithContentArgumentAndRenderStatic - How to manually set $contentArgumentName ?

### ISSUE THREAD

**Issue by AndreasA** [TYPO3/Fluid#351]
According the the comment for 
$contentArgumentName
one should prefer to set the value for it manually instead of using the autodetection.

However, I cannnot just add the value protected $contentArgumentName = 'foo'; to the class because that will result in a PHP fatal error because the properties are not the same.

Should one set it inside the initializeArguments method? If so, it requires documentation.

**Comment by NamelessCoder** [comment]
You can do this by setting `protected $contentArgumentName = 'myArgumentName';` in your ViewHelper class. When this property is not-empty, it gets used instead of trying to detect the name from the first optional argument.

**Comment by AndreasA** [comment]
Let me try to show my point with an example. After using "composer require typo3fluid/fluid"
Create a file test.php with the following content inside the composer root directory:

```
<?php
include __DIR__ . '/vendor/autoload.php';
class FooViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper
{
    use \TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithContentArgumentAndRenderStatic;

    protected $contentArgumentName = 'myArgumentName';

    public function initializeArguments()
    {
        $this->registerArgument('myArgumentName', 'string', '', true);
    }
}

new FooViewHelper();
```

Now if I execute "php test.php" the following PHP fatal error occurs:
```
PHP Fatal error:  FooViewHelper and TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithContentArgumentAndRenderStatic define the same property ($contentArgumentName) in the composition of FooViewHelper. However, the definition differs and is considered incompatible. 
```
Tested with PHP 5.6, 7.0 and 7.1

The reason is because I am not allowed to change the value of a property in the trait by the class that implements that trait:

What I can do is something like this:
```
<?php
include __DIR__ . '/vendor/autoload.php';
class FooViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper
{
    use \TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithContentArgumentAndRenderStatic;

    public function initializeArguments()
    {
        $this->registerArgument('myArgumentName', 'string', '', true);
    }
}
class BarViewHelper extends FooViewHelper 
{
    protected $contentArgumentName = 'myArgumentName';

    public function initializeArguments()
    {
        $this->registerArgument('myArgumentName', 'string', '', true);
    }
}

new BarViewHelper();
```

But that is why to complicated in order to achieve this.

Another solution might be to do this:
```
<?php
include __DIR__ . '/vendor/autoload.php';
class FooViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper
{
    use \TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithContentArgumentAndRenderStatic;

    public function __construct()
    {
        $this->contentArgumentName = 'myArgumentName';
    }

    public function initializeArguments()
    {
        $this->registerArgument('myArgumentName', 'string', '', true);
    }
}

new FooViewHelper();
```

or this:
```
<?php
include __DIR__ . '/vendor/autoload.php';
class FooViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper
{
    use \TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithContentArgumentAndRenderStatic;

    public function initializeArguments()
    {
        $this->contentArgumentName = 'myArgumentName';
        $this->registerArgument('myArgumentName', 'string', '', true);
    }
}

new FooViewHelper();
```

But I am not sure which one we are supposed to use. Or if not being able to override the contentArgumentName that way is actually a bug.

**Comment by NamelessCoder** [comment]
The solution here might be to add a method `protected function setContentArgumentName($name)` on the trait, which sets the internal property to a specific argument name. You'd then have to call this in `initializeArguments` - but that is logically where such an instruction belongs.

If you have time you are more than welcome to suggest that tiny change as a pull request ;)
