### ISSUE TITLE
Else with conditional does not behave as expected

### ISSUE THREAD

**Issue by georgringer** [TYPO3/Fluid#356]
In the following code, the condition of the @else@ seems to be ignored and the contents are always displayed.

```
<f:if condition="{p -> f:count()} == 1">
  <f:then>
    <f:render section='singleTable'/>
  </f:then>
  <f:else if="{p -> f:count()} > 1">
    <f:render section='multiTable'/>
  </f:else>
</f:if>
```

Adding an empty `else`  fixes the issue.

```
<f:if condition="{p -> f:count()} == 1">
  <f:then>
    <f:render section='singleTable'/>
  </f:then>
  <f:else if="{p -> f:count()} > 1">
    <f:render section='multiTable'/>
  </f:else>
  <f:else></f:else>
</f:if>
```

This is a copy of the original issue, located at https://forge.typo3.org/issues/83263

**Comment by stphnrdmr** [comment]
Thank you for copying the issue to the right place! Let me know if there are any further questions.

**Comment by jdreesen** [comment]
Which version of Fluid are you using? 
This sounds a lot like #284 which should have been fixed in #289 an was released in [v2.3.4](https://github.com/TYPO3/Fluid/releases/tag/2.3.4).

**Comment by stphnrdmr** [comment]
I'm using TYPO3 8.7.8 with the integrated fluid extension. I tried finding better info, but all I get is that it is version 8.7.8.

**Comment by jdreesen** [comment]
I assume you don't install TYPO3 via composer.
It seems that the TYPO3 v8.x version download bundles (zip / tar.gz) contain an outdated Fluid version without this patch (v2.3.1).

**Comment by NamelessCoder** [comment]
Hi guys - sorry to close this issue but the only way to solve this one is to update the Fluid dependency in TYPO3 CMS to at least 2.3.4 and have this included in the next generated distribution. Unfortunately, since you're not using composer, your only option for a quick fix is to apply the change from https://github.com/TYPO3/Fluid/pull/289/files manually.

**Comment by stphnrdmr** [comment]
Thank you @NamelessCoder!
