### ISSUE TITLE
Support HTTPS for xmlns ViewHelper NS registration

### ISSUE THREAD

**Issue by vertexvaar** [TYPO3/Fluid#359]
It took me some time to figure out why my ViewHelper didn't render until i debugged and found out `\TYPO3Fluid\Fluid\Core\Parser\TemplateProcessor\NamespaceDetectionTemplateProcessor::registerNamespacesFromTemplateSource` (Line 108) does only check for `http://typo3.org/ns/` but not `https://typo3.org/ns/`.
It would be really nice to have the HTTPS scheme supported :)

**Comment by mbrodala** [comment]
Thank you very much for your request. After a short discussion ([verdict here](https://github.com/TYPO3/Fluid/pull/360#issuecomment-353579429)) we came to the conclusion that we won't be adding this currently. Thanks for your understanding.
