### ISSUE TITLE
Viewhelper-> Problem with Cache and default Parameter

### ISSUE THREAD

**Issue by sir-script** [TYPO3/Fluid#365]
Hi guys, 

it looks like, that I've found a problem with the Viewhelper Cache Handling:
With the same input values, the non-Cached viewhelper render different argument values than the cached version of the ViewHelper.

My ViewHelper looks like this and is getting called with following arguments:
key = 'page'
treeRoot = NULL

Now I clear the system cache in the TYPO3 backend.
On the non-cached version, the var_dump outputs NULL for the argument "treeRoot".
On the other hand, the cached version accepts the default value and treeRoot becomes 0.

> <?php

namespace TYPO3\Bh\ViewHelpers\Tree;

use TYPO3\Bh as Bh;

class PageViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper {
	protected $escapeOutput = false;
	
    protected $pageRepository;
    protected $languageRepository;
    protected $activeLanguage;

	public function initializeArguments(){
		parent::initializeArguments();
		$this->registerArgument('key', 'string', 'The name of the iteration variable', false, 'item' );
		$this->registerArgument('treeRoot', 'int', 'Page ID', true, 0 );
	}

    /**
     * @return string Rendered string
     */
    public function render(){
        
        \TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($this->arguments['treeRoot']);
        
        $output = '';
        
        return $output;
    }
}

?>

The cached file looks like this:
[Page_action_tree_89fb278e2af865de533d9a31e8e39f033e84c6b4.txt](https://github.com/TYPO3/Fluid/files/1625699/Page_action_tree_89fb278e2af865de533d9a31e8e39f033e84c6b4.txt)

What do you think?

**Comment by webfacer** [comment]
hi did you solved this issue by yourself maybe? if yes do you know how to disable cache for a custom viewhelpr?

**Comment by NamelessCoder** [comment]
Your custom ViewHelpers can disable template compiling - but do so for the whole template file they're used in - if you implement the `compile()` method and from there, throw a `StopCompilingException`.

But perhaps the more appropriate solution is to use `renderStatic` instead. The issue was created before that time I think, but the `render()` method is now optional and the better choice is `renderStatic` which Fluid can natively compile in a more efficient way.

**Comment by sir-script** [comment]
@NamelessCoder @webfacer thank you for your advices. Yes, I've found a workaround for the specific viewhelper, on which the error originally appeared. 
@NamelessCoder thank you for your advice to use renderStatic instead. I'll try to prefer this method for our new viewhelpers ;).

**Comment by NamelessCoder** [comment]
Your ViewHelper also gives a default value to a non-optional argument which doesn't make much sense and likely confuses the resolving of the default value. I'll take the liberty of closing this as solved.
