### ISSUE TITLE
Log is spammed with is_dir(): open_basedir restriction warnings

### ISSUE THREAD

**Issue by liayn** [TYPO3/Fluid#366]
```
PHP Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (....) in /.../typo3_src-8.7.9/vendor/typo3fluid/fluid/src/View/TemplatePaths.php line 411
```

The reason is that the configuration of the extbase plugin's view look like this:
`plugin.tx_ext.view.templateRootPaths.10 = {$someEmptyConst}`

This results in `\TYPO3Fluid\Fluid\View\TemplatePaths::sanitizePath()` receiving `$path === ''` as parameter. This is furthermore converted to a `/` and a check with `is_dir('/')` is performed, which results in the above warning.

The proper solution would be to "reject" an empty path as it needs no sanitizing.

**Comment by liayn** [comment]
Sorry, incorrect report. Will improve it.

**Comment by liayn** [comment]
The actual issue is that an empty path is excepted and causes issues in TYPO3 core afterwards.
`\TYPO3\CMS\Fluid\View\TemplatePaths::getContextSpecificViewConfiguration`

My proposal is to fix this issue in Fluid, which should skip empty paths in general, as those do not make sense.

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/TYPO3/Fluid/commit/becacd0d58fcd75ae804816c66d1f2cb4667ebf8
