### ISSUE TITLE
ForViewHelper looses array keys with "reverse"

### ISSUE THREAD

**Issue by mmirsch** [TYPO3/Fluid#372]
When setting reverse="true" array keys get lost.
Example from DateMenu in tx_news:
<f:for each="{data.single}" key="year" as="months" reverse="true">

The problem is, that in Line 112 of the viewhelper class "array_reverse" is used without second argument:
112: $arguments['each'] = array_reverse($arguments['each']);

Instedad it could be solved with:
$arguments['each'] = array_reverse($arguments['each'],true);

Greetings,
Manfred

**Comment by mbrodala** [comment]
This is odd. What you write here perfectly makes sense but we even have a [unit test for this specific usecase](https://github.com/TYPO3/Fluid/blob/96c8c7d/tests/Unit/ViewHelpers/ForViewHelperTest.php#L167-L196). I'll have a look.

**Comment by mbrodala** [comment]
Seems to be working just fine:

```
$ cat template.html
<f:for each="{first: 1, second: 2, third: 3}" as="value" key="key" reverse="TRUE">
  {key}: {value}
</f:for>
$ bin/fluid --template template.html

  third: 3

  second: 2

  first: 1

```

Do you have additional details? What's in `{data.single}` in your example?

**Comment by tantegerda1** [comment]
From the php.net `array_reverse` [Documentation:](https://secure.php.net/manual/en/function.array-reverse.php)

> preserve_keys
>
>    If set to TRUE numeric keys are preserved. Non-numeric keys are not affected by this setting and will always be preserved.

Probably @mmirsch uses numeric keys while the unit test uses non-numeric ones?

**Comment by mbrodala** [comment]
@tantegerda1 This could be:

```
$ cat template.html
<f:for each="{0: 1, 1: 2, 2: 3}" as="value" key="key" reverse="TRUE">
  {key}: {value}
</f:for>
$ bin/fluid --template template.html

  0: 3

  1: 2

  2: 1

```

Numeric keys are indeed not preserved as per code and there is currently no test which checks the behavior here.

Now I'm unsure if we can just go and change this since it would introduce a change in behavior which can be unexpected to some. The current behavior can be desired e.g. if you want to use the keys as number prefixes for a listing (which can be done with `iteration` or `<ol>` in some cases too).

Personally I'm in favor of fixing this since that's what `reverse` promotes: `If TRUE, iterates in reverse`. @NamelessCoder what do you think?

**Comment by liayn** [comment]
Should definitely be fixed!

> The current behavior can be desired e.g. if you want to use the keys as number prefixes for a listing

Seems a bit theoretical to me.

**Comment by mmirsch** [comment]
> The current behavior can be desired e.g. if you want to use the keys as number prefixes for a listing

So you could add another option to decide wether array keys should be preserved or not?

**Comment by NamelessCoder** [comment]
My vote:

* Force keep keys when doing `array_reverse` as proposed in this patch.
* Prepare mentally for the day when such manipulations won't be the domain of the specific `f:for` or other array-consuming ViewHelper, but instead provided as native helpers (ViewHelpers, expressions, whatever) that can do things like reversing an array with and without protecting keys.
