### ISSUE TITLE
Cleanup Debug ViewHelper

### ISSUE THREAD

**Issue by markusguenther** [TYPO3/Fluid#376]
Little follow up from issue #375 

While adjusting this in the bugfix the wish popped up to have this clean up in a separate PR.
No PR without issue  ;)

**Comment by NamelessCoder** [comment]
On GitHub, a PR is technically also an issue - but it never hurts to have one of each :)

**Comment by lolli42** [comment]
Hmm. The PR has been closed. I guess it's fine to close here, too.
