### ISSUE TITLE
GroupedFor::groupElements Exception

### ISSUE THREAD

**Issue by ogrosko** [TYPO3/Fluid#383]
In `GroupedForViewHelper::groupElements` method there is an Exception 
`throw new ViewHelper\Exception('GroupedForViewHelper only supports multi-dimensional arrays and objects sdf', 1253120365);` if value is not array or object.

Woulnd't be better to skip this array value instead of throwing exception. Or maybe some option for ignoring empty values.

**Comment by mbrodala** [comment]
Silently skipping invalid items can quickly lead to errors which are hard to track down. The current behavior clearly tells you that your structure is not homogeneous and should be fixed. Can you add more details how your data structure looks like and at what point it fails?

**Comment by ogrosko** [comment]
My array looks like this:
![image](https://user-images.githubusercontent.com/2938503/38486415-474e4d9c-3bdd-11e8-9a57-6953d7b1abda.png)

btw: this array is comming from fluidtypo3 flux field with attribute `transform="TYPO3\CMS\Extbase\Persistence\ObjectStorage<Vendor\Ext\Domain\Model\Address>"`. Where null item is hidden or deleted.

**Comment by mbrodala** [comment]
An `ObjectStorage` never contains `null` values though. If this really is an array instead, you should [filter out the empty values](https://fluidtypo3.org/viewhelpers/vhs/master/Iterator/FilterViewHelper.html).

**Comment by ogrosko** [comment]
Yes temporarily I solve it by array_filter.
As you can see on screen it's an array no ObjectStorage

**Comment by mbrodala** [comment]
Since the `GroupedForViewHelper` has a single purpose, it should not contain any logic to clean up incoming homogeneous data structures. For that reason I don't think it would make sense to add options for this or for silencing the current error reporting. But thanks for reporting.
