### ISSUE TITLE
It would be nice if there were an ElseIf condition ViewHelper

### ISSUE THREAD

**Issue by albe** [TYPO3/Fluid#384]
Currently, nested if conditions in fluid templates become hardly readable pretty soon, either due to deep indentation or repeated opening of <f:if>:

``` html
<f:if condition="{a}">
<f:then>
A!
</f:then>
<f:else>
    <f:if condition="{b}">
    <f:then>
        B!
    </f:then>
    <f:else>
        <f:if condition="{c}">
        <f:then>
           C!
       </f:then>
       <f:else>
           D!
       </f:else>
       </f:if>
    </f:else>
    </f:if>
</f:else>
</f:if>
```

Hence I suggest adding a elseif condition to the if ViewHelper like this:

``` html
<f:if condition="{a}">
  <f:then>
    A!
  </f:then>
  <f:elseif condition="{b}">
    B!
  </f:elseif>
  <f:elseif condition="{c}">
    C!
  </f:elseif>
  <f:else>
    D!
  </f:else>
</f:if>
```

Copied from https://github.com/neos/flow-development-collection/issues/546

**Comment by jdreesen** [comment]
Fluid already allows this, see: https://github.com/TYPO3/Fluid/blob/5b6d5d3a48f4ea9e386a0584336801899d1d16f4/examples/Resources/Private/Singles/Structures.html#L51-L63

**Comment by albe** [comment]
Thanks for the heads-up! I already was kind-of expecting it, but didn't take the time yet to check deep enough and was just skimming through old issues on neos/flow-development-collection that could be closed/moved. Sorry for the fuss :)
