### ISSUE TITLE
media queries in css break the template parsing

### ISSUE THREAD

**Issue by vertexvaar** [TYPO3/Fluid#411]
I use a generated HTML template to send e-mails. The template is a single file that also contains the css in the html head. The dynamic parts are rendered with fluid. When replacing placeholders with fluid variables most of them will be printed as text instead of replaced with the actual value. I tracked this down to the style tag where media queries are used. When the media queries are removed all fluid variables will be rendered.

If you have more questions on the issue feel free to ask :)
(I can't provide the original template but i might be able to build one so you can reproduce the issue)

**Comment by vertexvaar** [comment]
BTW the workaround is to wrap the css in a CDATA section. I've found the resource on properly escaping CDATA in style tags here: http://www.webdevout.net/articles/escaping-style-and-script-data

**Comment by NamelessCoder** [comment]
CSS and JS is easily confused with Fluid code when parsing it - there is no way we can prevent this given the current inline syntax delimiters; it is a side effect of the way Fluid works. The solution is indeed to protect the CSS from parsing using one of three methods:

1. Enclose with CDATA.
2. Break patterns that are detected as Fluid with a ViewHelper, e.g. `f:format.raw`, by putting it around opening or closing braces.
3. Place the CSS in a partial file (you can name it `.css` but then you have to explicitly add the format in your `f:render` call when referencing the partial name) then put `{parsing off}` in that partial file.

Solutions 1 and 2 are appropriate if your CSS/JS has to use dynamic variables. Solution 3 is appropriate if the CSS/JS is entirely static.
