### ISSUE TITLE
MathExpressionNode called before any conditions

### ISSUE THREAD

**Issue by Atsyn** [TYPO3/Fluid#416]
Simplet template: `{f:if(condition: 0, then: '{a + 1}', else: 2)}`
Result: 
> #1476107295 TYPO3\CMS\Core\Error\Exception
> PHP Warning: A non-numeric value encountered in /var/www/clients/client1/web74/web/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php line 77

Why fluid try calculate math expression before check the condition?!

**Comment by mbrodala** [comment]
This has been discussed in #350 so you might want to have a look at that. Short version: the current behavior is by design albeit unexpected.

**Comment by Atsyn** [comment]
@mbrodala thx. I'm sorry for duplicate the issue.
