### ISSUE TITLE
Math expression allow only variables with Camelcase and not working with Snakecase

### ISSUE THREAD

**Issue by Atsyn** [TYPO3/Fluid#420]
I can't understand what wrong with Snake Case and why you not include it in pattern.

Database fields, in default, set in Snakecase it's mean "data" variable can't be used without additional manipulations.

One small fix in the regexp pattern should resolve it.

**Comment by liayn** [comment]
> I can't understand what wrong with Snake Case and why you not include it in pattern.

I guess this is simply a mistake. @NamelessCoder can for sure tell us more about that.

**Comment by mbrodala** [comment]
Yes, the `_` character is simply not accepted ATM:

https://github.com/TYPO3/Fluid/blob/f583bad/src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php#L28

@Atsyn can you open a PR to fix this?
