### ISSUE TITLE
f:security.ifAuthenticated AND .hasRole too heavily cached (TYPO3 9.5.3)

### ISSUE THREAD

**Issue by TokeHerkild** [TYPO3/Fluid#426]
In TYPO3 9.5.3 having tried to use both f:security.ifAuthenticated and hasRole, I've noticed that none of the render methods is actually rendered eg:
```
<f:security.ifAuthenticated>
    Dummy content only displayed if logged in
</f:security.ifAuthenticated>

<f:security.ifAuthenticated>
    <f:then>logged in</f:then>
    <f:else>not logged in</else>
</f:security.ifAuthenticated>
```
None of these possible rendering methods will get rendered, but If I replace:
TYPO3\CMS\Fluid\ViewHelpers\Security\IfAuthenticatedViewHelper.php line 60
```
return GeneralUtility::makeInstance(Context::class)->getPropertyFromAspect('frontend.user', 'id', 0) > 0;
// With this bad example
return intval($GLOBALS['TSFE']->fe_user->user['uid']) > 0;
```
Rendering methods works as expected.

**Comment by NamelessCoder** [comment]
This is unfortunately not an issue for TYPO3/Fluid, but for TYPO3 CMS. You should report this issue on https://forge.typo3.org/projects/typo3cms-core/issues.
