### ISSUE TITLE
f:variable fails with arrays

### ISSUE THREAD

**Issue by andreasfernandez** [TYPO3/Fluid#435]
Currently, Fluid passes the content of `f:variable` to `htmlspecialchars()` which leads to an error in case an array is passed.

The following code triggers the error:
```html
<f:variable name="years" value="{2: '2019', 3: '2020'}" />
```

The following error is thrown:
> PHP Warning: htmlspecialchars() expects parameter 1 to be string, array given in /var/www/html/vendor/typo3fluid/fluid/src/Core/ViewHelper/TagBuilder.php line 203

**Comment by NamelessCoder** [comment]
I assume this was a false positive that you identified pretty quickly ;) the hint is that the problem occurs in TagBuilder which isn't at all involved in `f:variable` or any code it calls.
