### ISSUE TITLE
Feature: Support variable extraction for classes with magic getter

### ISSUE THREAD

**Issue by cumuru** [TYPO3/Fluid#437]
Getting an object property via getter in a template fails if the getter isn‘t a native method but delegates the call via `__call()` instead.
This used to work in the TYPO3 CMS prior to v9 flavor of fluid as the variable provider was overridden by an own implementation that used other means of extracting values internally. 
This class was dropped here: https://review.typo3.org/c/Packages/TYPO3.CMS/+/54028

**Comment by NamelessCoder** [comment]
Solved via #438.
