### ISSUE TITLE
Use $_SERVER['REQUEST_TIME'] instead of time() for the current time in viewhelper f:date.format()

### ISSUE THREAD

**Issue by georgringer** [TYPO3/Fluid#441]
The Viewhelper f:date.format() use the time()-function, of PHP to get the current time.

$base = $arguments['base'] ?? time();

This line should be replaced by

$base = $arguments['base'] ?? $_SERVER['REQUEST_TIME'];

Reason: 
$_SERVER['REQUEST_TIME'] contains the starttime of the request. Every call of a Dateviewhelper will use the same 'current time'. 
If a user request a website at near midnight, two calls of time() can worstly generate two different dates with the f:format.date() viewhelper.

http://php.net/manual/en/function.time.php

See https://forge.typo3.org/issues/87935

**Comment by NamelessCoder** [comment]
Hi Georg,

`f:format.date` is part of TYPO3 CMS system ext Fluid - so https://forge.typo3.org/issues/87935 was actually the right place to report that. I'll close this issue and reopen the forge one ;)
