### ISSUE TITLE
SelectViewHelper render optgroups

### ISSUE THREAD

**Issue by Grigory-Rechkin** [TYPO3/Fluid#445]
I was looking for an option to create optgroups from ext:form .yaml configuration. Options are rendered by Form/SelectViewHelper. A part from `getOptions()`:
`$optionsArgument = $this->arguments['options'];`
`foreach ($optionsArgument as $key => $value) {`
`if (is_object($value) || is_array($value)) { ...`

An inner array is allowed but later there's no case to work with it and an exception is thrown:
`throw new \TYPO3Fluid\Fluid\Core\ViewHelper\Exception('No identifying value for object of class "' . get_class($value) . '" found.', 1247826696);`
And get_class will return an empty string so the exception is not even useful for this case.

Example of form .yaml to reproduce:
renderables:
      -
        properties:
          options:
            group1:
              value1: label1
              value2: label2
            group2:
              value3: label3
              value4: label4
        type: SingleSelect
        identifier: singleselect-1
        label: 'Single select'

I would like to suggest a fix but it needs to be checked:
`if (is_array($value)) {`
`                foreach ($value as $innerKey => $innerValue) {`
`                    if (!strlen($innerKey) || !strlen($innerValue)) {`
`                        throw new \TYPO3\CMS\Fluid\Core\ViewHelper\Exception('Only a string and numeric type values are allowed for options inside an optgroup', 1247827554);`
`                    }`
`                }`
`            }`

And replace `renderOptionTags()`:
`protected function renderOptionTags($options)`
`    {`
`        $output = '';`
`        foreach ($options as $value => $label) {`
`            if (is_array($label)) {`
`                // $value is an optgroup name`
`                // $label is an array of inner options`
`                $output .= '<optgroup label="' . htmlspecialchars($value) .'">';`
`                $output .= $this->renderOptionTags($label);`
`                $output .= '</optgroup>';`
`            } else {`
`                $isSelected = $this->isSelected($value);`
`                $output .= $this->renderOptionTag($value, $label, $isSelected) . LF;`
`            }`
`        }`
`        return $output;`
`    }`

**Comment by NamelessCoder** [comment]
Hi @Grigory-Rechkin,

This is the wrong issue tracker - your request pertains to TYPO3 CMS, not the Fluid template engine itself. Please recreate it at https://forge.typo3.org/projects/typo3cms-core/issues.
