### ISSUE TITLE
Bugfix "Escaping of escapable ExpressionNode" breaks templates with JavaScript

### ISSUE THREAD

**Issue by runner78** [TYPO3/Fluid#452]
After Upgrade to TYPO3 9.5.6 with Fluid 2.6.1, i have an error with templates with JavaScript.

> at TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'Invalid argument supplied for foreach()', 'vendor/typo3fluid/fluid/src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php', 180, array('templateSource' => '<f:layout name="Default"/><f:section name="header"></f:section><f:section name="main"> <script type="text/javascript"> function initMarker(map) { var markerImage = new google.maps.MarkerImage(imagePin, new google.maps.Size(24, 50)); for (var i = 0; i < markers.length; i++) { var point = new google.maps.LatLng( parseFloat(markers[i].position.lat), parseFloat(markers[i].position.lng)); var marker = new google.maps.Marker({ map: map, position: point, icon: markerImage }); parsedMarkers.push(marker); } } </script></f:section>', 'viewHelperResolver' => object(TYPO3\CMS\Fluid\Core\ViewHelper\ViewHelperResolver), 'splitTemplate' => array('', '<f:layout name="Default"/>', '', '<f:section name="header">', '', '</f:section>', '', '<f:section name="main">', ' <script type="text/javascript"> function initMarker(map) { var markerImage = new google.maps.MarkerImage(imagePin, new google.maps.Size(24, 50)); for (var i = 0; i < markers.length; i++) { var point = new google.maps.LatLng( parseFloat(markers[i].position.lat), parseFloat(markers[i].position.lng)); var marker = new google.maps.Marker({ map: map, position: point, icon: markerImage }); parsedMarkers.push(marker); } } </script>', '</f:section>', ''), 'templateElement' => ' <script type="text/javascript"> function initMarker(map) { var markerImage = new google.maps.MarkerImage(imagePin, new google.maps.Size(24, 50)); for (var i = 0; i < markers.length; i++) { var point = new google.maps.LatLng( parseFloat(markers[i].position.lat), parseFloat(markers[i].position.lng)); var marker = new google.maps.Marker({ map: map, position: point, icon: markerImage }); parsedMarkers.push(marker); } } </script>', 'matchedVariables' => array(), 'sections' => false, 'section' => ''))

**Comment by Patta** [comment]
I use style tags in some fluid layouts. After update to 8.7.25, the output is broken and a comparable warning is shown in be log .

**Comment by bmack** [comment]
Can you confirm that it worked in PHP 7.3.4?

If so, this is related https://www.php.net/ChangeLog-7.php#7.3.5 and https://bugs.php.net/bug.php?id=77827 - I would say.

**Comment by bmack** [comment]
Can you also paste the Fluid template that is used?

**Comment by Patta** [comment]
@bmack 
Iam pretty shure before 7.3.5 everything works good.

It turns out that the warning comes not from the style element in the fluid mail layout. It comes from the fluid template main section and only in extension fluid templates, not in content element or page templates and not in layouts (in my tests).

You can test it in debug mode with e.g. `exceptionalErrors = 28930` the warning appears, with `exceptionalErrors = 4352` the output is broken.

Input the following style element in an extension fluid template main section (e.g. [this](https://github.com/FriendsOfTYPO3/tt_address/blob/master/Resources/Private/Templates/Address/List.html)) and you should see the error/warning.

```
<style>
  .something {
    background-color: red;
  }
</style>
```

**Comment by DavidSporer** [comment]
I can confirm that this is caused by the bug in PHP 7.3.5 that is linked above.
We're using Fluid in a Flow project and experienced this issue when trying to upgrade to PHP 7.3.5.

**Comment by bmack** [comment]
so let's create a UnitTest for Fluid Standalone to check that use-case, so we're sure we can fix it properly.

**Comment by kdambekalns** [comment]
Workaround: wrap the offending section into CDATA…

**Comment by Patta** [comment]
@kdambekalns your workaround are not working for me, the wrapped styles are removed.

**Comment by Patta** [comment]
> I use the style element in some plugin fluid templates and layouts for mails.
> After update to PHP 7.3.5, the output is broken and a comparable warning is shown in be log:
> `Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /<REMOVED>/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php line 591 `
> `Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /<REMOVED>/vendor/typo3fluid/fluid/src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php line 180 `
> 
> Temporary fix: Moving styles from the <style> element in the fluid templates to a external file and remove the <style> rules to (only) inline styles in the fluid mail layouts.

With TYPO3 9.5.13 i can not reproduce that error messages or a broken frontend.
The only thing that still broke the output are mail layouts that contains @media rules in the style tag.

**Comment by lolli42** [comment]
So this was probably an issue in PHP, most likely https://bugs.php.net/bug.php?id=77827
It should be long resolved now and i guess it's fine to close here.
