### ISSUE TITLE
Tasks during Fluid 3.0 workshop

### ISSUE THREAD

**Issue by NamelessCoder** [TYPO3/Fluid#458]
This issue is intended to outline a set of tasks and sub-tasks that should be done on the Fluid 3.0 workshop on June 20-22 2019. **Documentation tasks are in bold** and _development tasks are in italics_.

### Documentation-specific

* [x] **XSD capability research**
  * [x] **Can we get better type hints? AnySimpleType vs. object name for example**
  * [x] **Can/should we document which type of nodes are allowed inside others (currently handled by exceptions)**
    * [ ] _evaluate how to implement researched capabilities_
    * [ ] _evaluate how to document Component composition as namespace_
* [x] **Rendered ViewHelper documentation** 
  * [x] **Discuss format: Markdown, RST, plaintext, external-arbitrary?**
  * [ ] _refresh namelesscoder/typo3-fluid-documentation-generator and maybe import to TYPO3_
* [x] **Main usage documentation**
  * [x] **Discuss and create ideal flow through "learn Fluid" from integrator's perspective**
  * [ ] **Where to put docs - cross-link to TYPO3 docs**
  * [ ] _evaluate whether automation can assist with things like code examples_
  * [ ] **Discuss and create detailed reference-style docs** - _from developer perspective, e.g. how to extend Fluid or use low-level API_
  * [ ] **Best practice for templates, third-party components and so on**

## Meta-development

* [x] _Rename to `typo3/fluid-engine`_ and **discuss how to best communicate this change**
* [x] _Upgrade PHPUnit_
* [x] _Walkthrough: Sequencer_
  * [ ] **New handling of edge cases like JS/CSS is vital to document**
  * [x] _New abilities without regular expressions_
  * [x] _Discuss/refactor pre-processors to "node visitation" or built-in features_
    * [x] _Discuss possibility to leverage ViewHelpers to also support Expressions and more_ 
* [x] **Discuss whether to drop MVC-centric resolving and leave this up to implementer/framework (drop notion of Package, Action and Controller names in Fluid itself - permit just "file" as entry point). Can be 1:1 restored in TYPO3 CMS and Neos (we lack Neos people as participants)**
* [x] _Discuss compiling strategy. Current: developer makes strings containing PHP code that ends up in compiled PHP class. Future possibility: Fluid auto-creates Nodes also in compiled state, and we make the node creation process efficient enough to be comparable to current strategy._
  * [x] **Effect A: a ViewHelper would no longer be in any way static, and instance would have child nodes and everything**
  * [x] **Effect B: a ViewHelper has only one way to render and it always has the same properties filled**
  * [x] **Consequence: we can completely remove every PHP-compilation measure such as child node compiling in condition or switch ViewHelpers; condition ViewHelper code base would likely be 25% or less of current size**
* [x] _Discuss alternative to storing PHP classes - for example, might the new strategies allow a serialized representation of the node tree to be stored, meaning the compiler is essentially redundant?_

Notes: the package rename is requested from TYPO3 and we will happily oblige. PHPUnit is already upgraded to a version that's ready for strict types. The Sequencer is a new feature I've built for Fluid to replace the regular expressions mechanism we use today - it has a bunch of very positive effects that we can leverage for new, flexible features to control Fluid.

MVC is good but we may be able to avoid this decision on behalf of implementers (see below re: template types reduction). If we remove this, the interface between framework and Fluid will simply be "I need to render this file, here are the paths it may exist within".

Finally, the compiler logic change is worth considering - one of the weak points of Fluid currently is that writing a truly good integration for a complex ViewHelper (case in point: the switch ViewHelper) requires some pretty detailed knowledge of *exactly* what to return and which methods to use. If we are able to represent a "compiled" template exactly the same as the uncompiled version of it - as a tree of nodes, ready to be evaluated - this *should* perform comparably and would drastically decrease the knowledge required to, for example, write a ViewHelper that does advanced stuff with child nodes (all the current "compile to closure" basically goes away, static rendering no longer sensible).

## Development

* [x] _Type strictness: do not apply to legacy classes_
* [ ] _API Unification - Components_
  * [x] **Walkthrough: ViewHelperDocumentation and ArgumentCollection**
  * [x] _Parameterised Template Files - allow a Component (file) to provide ArgumentCollection containing required/default arguments and types, just like a ViewHelper_
  * [ ] **Discuss how to best document this capability: what must integrators look for? How will developers create?**
  * [ ] **Discuss strategy to render insights as backend module; list and document all Fluid template files and their arguments**
  * [x] _Introduce new replacement interface and component bases_
    * [x] _Refactor argument handling to ArgumentCollection_
    * [x] _Refactor or extend ParsedTemplate and others from new interfaces/bases_
  * [x] _Switch to replacement interfaces_
    * [x] _Add temporary side support in TemplateParser and others (substitute classes?)_
    * [x] _Switch ViewHelpers and template-level features to new interfaces_
* [ ] _Argument handling: transparently allow any component that has an array-typed argument, for example named `myArray`, to pass that array using `myArray-key="value"` as well as `arguments="{myArray: {key: value}}"` (make tag-based ViewHelper's argument handling the standard)_
* [ ] **Discuss whether to deprecate the tag based ViewHelper concept entirely and make the "I render tags" completely up to the ViewHelper (one effect: a "link" ViewHelper can be a subclass of the "uri" counterpart with added arguments for the tag attributes and a render method that renders parent to generate the URI and creates a tag with that in href)**
* [x] _Discuss whether to make every component potentially a conditional component. Essentially, making it possible for any component to add a `verdict()` method which if false, causes the component to not render (default implementation)_
  * [x] _Current condition ViewHelper then either renders then/else or child nodes instead of either rendering or not rendering_
  * [ ] _Effect: disable rendering of a tag+body, section, whatever, by changing the value of an argument - possibly a universal argument (or one that can be toggled on per-template, as per Sequencer's feature handling)_
  * [ ] _Potential consequence: drastically reduced need for `f:if` across all Fluid templates; most frequent use case of "only output this if this is true" may be native to any and all ViewHelpers_
  * [ ] _Option: let any ViewHelper that has a `verdict()` method also support `f:then` and `f:else` child nodes_

Notes: as for type strictness, it makes little sense to apply this to our legacy classes - instead we can focus on strictness for newly added classes only. After the component feature is completed we can then harden the public remaining API that isn't deprecated.

The refactoring to ArgumentCollection is meant to give a DTO-like object that's easier to exchange from other components than only ViewHelpers. This means a parsed template can also return an ArgumentCollection which internally holds the definitions for arguments (variables) it requires, using ArgumentDefinition like ViewHelpers do today, and also contains the necessary logic to evaluate arguments, validate argument presence and throw exceptions on problems.

This new reflection-like insight for templates can (should?) then be possible to render as a reference in a backend module or export to an XSD (depending on how we integrate, a template could for example be rendered with `<custom:somePath.someFile arg1="foo" />` which means we can collect the "atoms" of a given namespace and document their arguments as if they were a collection of ViewHelpers.

There are also implications for design systems; they would be capable of defining default values of all variables that are optional - and only create variable mockups of those that are mandatory.

Finally there are implications for extended lint features to verify that every required argument is passed to a template.

## Deprecations / important changes

* [x] _Deprecate nearly all existing node types (ViewHelpers are nodes are components, no distinction)_
* [x] _Deprecate old interfaces fully_
* [ ] **Deprecation documentation with links to replacement feature docs**
  * [ ] **JS/CSS handling and new escaping strategy**
* [x] **Sequencer: quote escaping no longer matters**
* [x] **Sequencer: backslash escaping of opening curly is new method to ignore inline**
* [ ] **Sequencer: document ViewHelper aliasing ability**

## Side-quest: atomic logic

* [x] _Replace Template, Layout, Partial with "Atom" and reduce number of template path sets to one set_
  * [x] _Deprecate/remove template-type-specific functions from TemplatePaths_
  * [x] _Change TemplateParser-to-TemplateCompiler relationship so TemplateCompiler is, as far as possible, aware of file name (made significantly easier by only having one type of template file)_
  * [x] _Implement compatibility mode/toggle that reads Template, Layout, Partial from within "resource root paths"_
  * [x] _Implement new ways to "use atom as layout" (extend) to replace Layout logic_
  * [x] _Discuss how Sections should be handled when extending, rendering, importing - should a Section be an Atom?_
  * [x] **Discuss how to document such a change - and new best practice. No longer constrained to just three types of templates, no distinction between where a template is - only distinction is in HOW a template is used**
  * [x] _Discuss TYPO3-specific way to provide new singular resource path sets as global configuration - removing the current TS-native approach_
  * [x] _Deprecate current path settings and logic_

## Side-quest: rewrite compiling strategy

* [x] _Change the way Nodes compile to PHP - the resulting PHP should instead re-create nodes and do things like assign child nodes_
  * [x] _Utilise reduced number of node types from API unification (a VH node can be created by creating the instance of the ViewHelper directly!)_
  * [x] _Utilise ArgumentCollection to decouple all argument handling (if possible, no need to compile arrays anymore: an argument value can be a node, the ArgumentCollection can evaluate it to generate the actual arguments array based on current rendering context / variables etc.)_

**Comment by lolli42** [comment]
Hey.
Since this is related to the stalled fluid v3 development, I hope it is ok to close here for now according to the reasoning outlined in https://github.com/TYPO3/Fluid/issues/591.
