### ISSUE TITLE
Problematic regular expression in StandardVariableProvider for resolving sub variable references

### ISSUE THREAD

**Issue by FelHell** [TYPO3/Fluid#471]
There seems to be an issue with multiple variables in the arguments of a `<f:render partial="...">` tag. The following Fluid template demonstrates the problem:
```html
<f:variable name="entity" value="{text_lorem_ipsum: 'Lorem Ipsum Dolor Sit Amet'}" />
<f:variable name="key1" value="lorem" />
<f:variable name="key2" value="ipsum" />

Correct output:
<f:render partial="DummyPartial" arguments="{text: entity.text_lorem_ipsum}" />

Correct output:
<f:render partial="DummyPartial" arguments="{text: '{entity.text_lorem_{key2}}'}" />

No output (text is NULL):
<f:render partial="DummyPartial" arguments="{text: '{entity.text_{key1}_{key2}}'}" />
```
The `DummyPartial` simply outputs `{text}`.

I think that the regular expression doesn't work here for multiple variables:
https://github.com/TYPO3/Fluid/blob/865890c3cffaf8d5f6aa44295d42a84a103895ec/src/Core/Variables/StandardVariableProvider.php#L258

**Comment by NamelessCoder** [comment]
Just for the record: this is a known limitation and it is unlikely to be solved by modifying the regular expression. Business logic around the extraction also has to change - and I really hesitate to make this truly recursive (our history with regular expression as solution is less than ideal...)

Also for the record: this will be a complete non-issue in Fluid 3.0 which will support any level and combination of dynamic variable access, including use of inline VH inside.

**Comment by albe** [comment]
Yeah, this solves only one specific corner-case of variables within expressions. Something like `_{key1{key2}}` still wouldn't work (though arguably that is stretching things a bit anyway). But IMO the "solution" (making the inner match greedy) is minimally invasive and also improves the regex performance for common match cases. So it could still be considered, but ofc decision is up to @NamelessCoder

**Comment by NamelessCoder** [comment]
Apologies to @FelHell for rejecting this. Don't let this discourage you from future pull requests!

Reasons given:

* Inability to extract multiple same-level variables is a known limitation of Fluid 2.x and earlier
* Changing this also implies a need to change a lot more regarding how variables are resolved
* It is a non-issue in the next major version of Fluid, 3.0
