### ISSUE TITLE
Suggestion: introduce mutation testing to increase tests relevance

### ISSUE THREAD

**Issue by romm** [TYPO3/Fluid#473]
Tests code coverage is a nice metric, but not the best one to show how strong and relevant a test suite is.

Mutation Score Indicator is a better metric because mutation testing catches parts of the code that are actually not tested (or "badly").

Fluid 3.0 reaching 100% code coverage is an excellent opportunity to introduce mutation testing.

Currently, the best PHP tool for this is [Infection](https://github.com/infection/infection/). It works very well (while being a bit slow) and provides enough mutators to strongly reinforce Fluid's test suite.

I've been running it on Fluid 3.0 master branch and got the following result (see below). ~70% MSI is a good score for a beginning and could be improved in the future.

What are your thoughts on this?

![image](https://user-images.githubusercontent.com/6342901/63780490-7ad10f80-c8e8-11e9-9367-da337ea8335a.png)

**Comment by lolli42** [comment]
Hey.

It seems currently nobody is working on an implementation like this. I guess we could close here for now and pick up in a new issue or re-open in case we really want to add and maintain this.
