### ISSUE TITLE
Wrong type annotation in NamespaceDetectionTemplateProcessor

### ISSUE THREAD

**Issue by andreasfernandez** [TYPO3/Fluid#476]
The property `NamespaceDetectionTemplateProcessor::$localNamespaces`is annotated as `array()` which breaks with newer releases of phpdocumentor/reflection-docblock used in TYPO3 v10:

> A type is missing in an array expression

xdebug reveals that the exception is thrown due to this annotation.

**Comment by NamelessCoder** [comment]
Merged.
