### ISSUE TITLE
f:format.nl2br() outputs encoded <br/>

### ISSUE THREAD

**Issue by Geddo** [TYPO3/Fluid#481]
I just updated an 8.7 installation from fluid 2.4 to 2.6.

f:format.nl2br() now outputs encoded BR-Tags (&lt;br/&gt;), for e.g. I need to add f:format.raw() to my templates now:

```
{data.header -> f:format.nl2br() -> f:format.raw()}
```

**Comment by mbrodala** [comment]
What exactly is the content of `data.header` and what exactly do you get as output (HTML code) without `f:format.raw()`?

**Comment by Geddo** [comment]
Had this in my Header:
`TESTHEADER<br/>TESTHEADER ZWEITE ZEILE`

Got this in my Output (HTML)
`TESTHEADER&lt;br/&gt;TESTHEADER ZWEITE ZEILE`

In my template I had this one:
`{data.header -> f:format.nl2br()}` which seems also to render `<br/>`-Tags correctly in the previous versions, but after an update the `<br/>`-Tags were visible in the FE which is actually correct behavoir  so I even cannot say it's a bug, it's just a change in the rendering behavoir.

to make matters worse this all belong to a Flux-Element so I dunno if this change comes from fluid or flux (since I got other problems here too). So for now I just will close this.
