### ISSUE TITLE
StandardVariableProvider can't handle magic functions as accessor

### ISSUE THREAD

**Issue by bartbrouwer** [TYPO3/Fluid#494]
StandardVariableProvider is using method_exists to check if there is a getter. We have to use is_callable so it can handle magic functions (__call)

**Comment by NamelessCoder** [comment]
See https://github.com/TYPO3/Fluid/pull/489 and related issues, there's a lot of back story as this was previously attempted - the short version: this and other magic method support variables won't be fixed as it has a number of side effects.
