### ISSUE TITLE
Possibly non defined renderingContext key

### ISSUE THREAD

**Issue by alexanderschnitzler** [TYPO3/Fluid#497]
This check in `\TYPO3Fluid\Fluid\View\AbstractTemplateView::getCurrentRenderingContext` is failing with PHP 7.4 if the key `renderingContext` is not set:

```
return $currentRendering['renderingContext'] 
    ? $currentRendering['renderingContext'] 
    : $this->baseRenderingContext;
```

Could be solved this way:

```
return ($currentRendering['renderingContext'] ?? null) 
    ? $currentRendering['renderingContext'] 
    : $this->baseRenderingContext;
```

**Comment by NamelessCoder** [comment]
We still must support PHP 5.x on the 2.x branches of Fluid. When 3.0 arrives there are *many* places we could switch to null coaleasce!

PR #499 merged - closing the issue.
