### ISSUE TITLE
custom ViewHelper is not executed on page reload

### ISSUE THREAD

**Issue by smoebody** [TYPO3/Fluid#500]
After migrating my custom extension from typo3 7.6 to typo3 8.7 i encounter a strange behavior.

When i load the page with the extension-plugin the first time (or after flushing *all* caches) my custom view helper "myCustomViewHelper" gets invoked and fills the `div` with the right content ('foobar').
When i reload the page, the view helper is not invoked at all (i tested with xdebug) and the div has no content.

The template (simplified): 
```fluid
{namespace helpers=My\Extension\ViewHelpers}
<f:layout name="Default" />
<f:section name="main">
					<div>{helpers:myCustom()}</div>
</f:section>
```

The helper (simplified):
```php
<?php

namespace My\Extension\ViewHelpers

class MyCustomViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractConditionViewHelper {

	/**
	 * initialize Arguments
	 *
	 * @return void
	 */
	public function initializeArguments() {
	}

	/**
	 * Returns 'foobar'
	 *
	 * @return string
	 */
	public function render() {
		return 'foobar';
	}
}
```

I have no idea what is cached and where i can change that behavior.

The only thing i know about is the file `ext_localconf.php` where i configure my plugin with the cachable and uncachable controller-actions, but i haven't changed it regarding the migration to 8.7, and it works in 7.6. It looks like this:
```php
TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
	'My.Extension',
	'CustomPlugin',
	[
		'CustomController' => 'customAction',
	],
	[
		'CustomController' => 'customAction',
	]
);
```

Any  help would be appreciated.

**Comment by smoebody** [comment]
Ok, now i see the relation to #259. Closing

**Comment by NamelessCoder** [comment]
In this case, your mistake is to use the base AbstractConditionViewHelper but override the `render` method which completely disables all condition logic in compiled templates.

If your VH is supposed to be a condition, implement `evaluateCondition`.

If not, use the simpler AbstractViewHelper as base class.
