### ISSUE TITLE
Release to support PHP 7.4?

### ISSUE THREAD

**Issue by kdambekalns** [TYPO3/Fluid#501]
With the master version I could use PHP 7.4 just fine, what are the plans for a release? Any blockers you need help with?

**Comment by NamelessCoder** [comment]
Hi @kdambekalns,

Due to time constraints a new release is not planned until (at or right around) December 12th.

If necessary I can create a release sooner than this. To my knowledge, there are no remaining PHP 7.4 incompatibiities!

**Comment by kdambekalns** [comment]
> If necessary I can create a release sooner than this.

Oh, well… _necessary_, what does that really mean… 😉  It would be great to have it, but if you lack the time do release, then that's how it is.

If it happens faster, I'd be happy, if not, I'll be looking forward to December 12th… 🎉 
> To my knowledge, there are no remaining PHP 7.4 incompatibiities!

That is already awesome in itself! ❤️

**Comment by NamelessCoder** [comment]
Hey @kdambekalns - I've tagged 2.6.8 today since a bug fix release of TYPO3 is coming on Tuesday which needs the php 7.4 fixes.
