### ISSUE TITLE
Formatting issues in ViewHelper reference - pragmatic suggestion

### ISSUE THREAD

**Issue by sypets** [TYPO3/Fluid#512]
The topic of Fluid VH reference reST vs. markdown etc. has been discussed at length. We still have the automatically generated typo3fluid VH which looks pretty ugly, because the rendering toolchain expects reStructuredText at some point and the source was written as Markdown. Last status was, we cannot easily fix this at this point (unless someone is willing to work on the scripts. I don't know how difficult or complicated this might be). 

Now I came across this [if-VH page](https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/If.html) which looks partly quite ok, when rendered on docs.typo3.org.

So, can we use a reasonable subset of markup that looks ok - whether it is interpreted as reST or Markdown? Incidentally, I found this resource [Markdown and reStructuredText](https://gist.github.com/dupuy/1855764) a while ago.

-----

For **headers**, we an use underlining which is ok in both worlds, see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers

```
header
=====
```

Also, instead of headers we can use bold (`**bold**`) which is also ok in both worlds

There is no really good solution for **links** (but we usually don't use links in the VHs)

For **lists** we can use * list item 1 etc. which is ok (reST is just really picky, you MUST have an empty line before and after). 

```
* list item 1
* list item 2
```

For code-blocks there is a nifty solution in the mentioned resource:

> you can combine the formatting for both of them by ending one paragraph with a double colon :: (for reStructuredText) and indenting the next one by four or more spaces (for Markdown) to make it appear in monospaced font without flow or word-wrapping:

example:

```
some example code::

    <f:if condition="{whatever} == 'notever'">
```

**Comment by sypets** [comment]
This is the mentioned if-ViewHelper page which is already rendered partly ok: 

* on docs.typo3.org: https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/If.html
* the source: https://github.com/TYPO3/Fluid/blob/master/src/ViewHelpers/IfViewHelper.php

![example3](https://user-images.githubusercontent.com/13206455/74746376-a3b5da00-5265-11ea-8a7f-6c5cead3d93a.png)

**Comment by mbrodala** [comment]
Interesting approach to improve the current state. :-)

Explicitly customizing the code block highlighting (code language) won't be possible with this, right?

Markdown uses this:

```
```<language>
<code>
```

ReST uses this:

```
.. code-block:: <language>

   <code>
```

At least for ReST we could use the [Highlighting directive](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/Codeblocks.html#highlight-directive) on a doc page though.

**Comment by sypets** [comment]
You are right. The suggested usage of `::` will only work with syntax highlighting for the default language (which is specified in the Includes.txt or a highlight directive in the respective file in the TYPO3 docs). Currently, this is usually PHP. 

For the ViewHelper ref, XML could be used as default language. I browsed through the examples. It seems that all code blocks are using a Fluid snippet or inline notation. This currently renders fine with syntax highlighting, see https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3/backend/latest/Avatar.html

Not sure, what is currently specified as default language in the VHref as it is automatically generated.

If all code-blocks are in one language we should be fine without specifiying the language. (As far as I have seen, most code blocks in the ViewHelpers currently do not specify the language either).

I am not a **Markdown** guru, but AFAIK, you can use any of these in Markdown:

* indent the text
* use backticks (for inline code) or three backticks for code blocks

This does not allow the possibility to specify the language

* or use `<code>` as you wrote. 

In **reST / sphinx** you can use either:

* ["literal block"](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks):  `::`
* or `.. code-block:: `language (actually, this is not pure reST, I think. It is a sphinx directive)
* or` .. code:: language` (this is a docutils directive, I think)

**Comment by NamelessCoder** [comment]
Couple of questions about RST:

* Is the "literal block" `::` truly, completely required? If intendation is sufficient (and highlights in default language and that is set to XML) then this is compatible with Markdown.
* Is inline code block truly, completely required to use double backticks around the inline code? If it can work with a single backtick, which I believe it can - then that too is compatible with Markdown.
* Do we really require custom formatting such as `.. note::` or would this also be possible with other formatting, e.g. italic blocks?

Particularly, If the last one about `.. note::` is entirely sphinx-only then I would certainly avoid that as it would be far too opinionated, much worse than just the RST vs. Markdown discussion!

The thing is, if we use only the most basic visual formatting we could preserve the ability to render with either RST or Markdown, whichever people prefer. For me personally I am completely fine not being able to, for example, perform syntax highlighting but instead just render a code block as monospaced (like it happens for example on GitHub).

For example...

----------------------------------------------------

Some title
----------

    This is indented with four spaces and renders as monospace.
    It renders line breaks explicitly

More text to describe stuff.  Also `inline code` that we like.

    Another code example

----------------------------------------------------

In source this is written as:

```plain
Some title
----------

    This is indented with four spaces and renders as monospace.
    It renders line breaks explicitly

More text to describe stuff. Also `inline code` that we like.

    Another code example
```

If RST is capable of rendering that in the same way Markdown would render it, I think the decision is sort of made for us: there's no good reason to insist on special RST or even sphinx-only formatting, if a simpler variant...

1. Can be rendered by RST.
2. Can be rendered by Markdown.
3. Looks good as plaintext (which is what an IDE would display, for example).
4. Is significantly easier to contribute to since you need to know just 4-5 basic formattings.

I would find it more than reasonable to sacrifice code highlighting, "note" and various "danger, warning, info" etc. color blocks in favor of supporting multiple renderings and especially also supporting plaintext viewing.

**Comment by sypets** [comment]
I wouldn't worry too much about things that are not really used very much in the VH code, e.g. the notes and inline code. If you ask me, the hints, notes etc. are currently being a bit overused (though I am guilty of this myself).

> Is the "literal block" `::` truly, completely required?

I am afraid so. IMHO the combination :: and indenting seems a good way to go. Often you have a snippet after a sentence ending with a colon, so you can write this pretty organically:

```
See the following cool example::

   <f:coolExample/>

```
Without having to worry about reST support, it would look like this:

```
See the following cool example:

   <f:coolExample/>
```

I would agree that having a single :: on a line by itself takes getting used to:

```
We have some examples.

::

    <f:coolExample/>
```

> Is inline code block truly, completely required to use double backticks around the inline code?

Single backticks should work (though we mostly used double backticks or single backticks in combination with [explicit textroles](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/InlineCode.html)). If you are really, really nitpicky, you might have a problem with that because single back ticks are semantically ["Interpreted text using the default role"](https://stackoverflow.com/questions/10870719/inline-code-highlighting-in-restructuredtext). If you render with our toolchain and without Includes.txt you apparently get the textrole "cite" (look at the HTML source of a page rendered with our toolchain).

----

I supplied a very [minimal git repo](https://github.com/sypets/RstMarkdownExample). You can play around with it and render the reST / sphinx locally (and see the Markdown rendering on GitHub):

```
git clone https://github.com/sypets/RstMarkdownExample.git
cd RstMarkdownExample
source <(docker run --rm t3docs/render-documentation show-shell-commands)
dockrun_t3rd makehtml
open "file:///$(pwd)/Documentation-GENERATED-temp/Result/project/0.0.0/Index.html"
```

see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/RenderingDocs/Index.html

----

I will ask @marble to have a look and see if he would have a different opinion on any of this. 

----
Again, thank you for your patience and the work you do.

**Comment by NamelessCoder** [comment]
> `See the following cool example::`

The double colon is perhaps the least troublesome of these, mainly I'm worried that people wouldn't know why/when to use those.

> Single backticks should work [...] If you render with our toolchain and without Includes.txt you apparently get the textrole "cite" (look at the HTML source of a page rendered with our toolchain).

Couldn't this be resolved by always prepending the "includex.txt" to generated VH docs? We certainly don't want to have to put that inclusion line in all phpdocs! In VH docs we have no real use for `cite` so forcing that to be "something else" would be okay imho.

> I wouldn't worry too much about things that are not really used very much in the VH code, e.g. the notes and inline code. If you ask me, the hints, notes etc. are currently being a bit overused (though I am guilty of this myself).

I worry about those ;) my goal here is mainly to ensure that Fluid remains a framework-agnostic package and using sphinx-only markup, or markup that depends on a particular inclusion, would be contrary to that goal.

> Again, thank you for your patience and the work you do.

You're very welcome!

**Comment by sypets** [comment]
I would not suggest adding the Includes.txt to the phpdoc either. As you pointed out that can be added later when generating. And, at this point I do not think it is even strictly necessary. 

>> I wouldn't worry too much about things that are not really used very much in the VH code

> I worry about those ;

To state it more clearly: Do not worry about markup that is not even being used and that no one is insisting on using in the phpdoc (in Fluid source code).

> my goal here is mainly to ensure that Fluid remains a framework-agnostic package and using sphinx-only markup, or markup that depends on a particular inclusion, would be contrary to that goal.

Understood and agreed.

You are right, there is a possible confusion: If people assume we use the same markup in the phpdocs as is being used in the official TYPO3 documentation.

What I would do is add guidelines to the contribution information in your repo (e.g. CONTRIUTING.md or similar). I think it would actually be simpler for contributors if we use simple restricted markup as suggested in this issue. 

In my experience: If things are already done consistently in the code (and it is not too complicated and weird), contributors will usually do it correctly. 

I do think we have 2 advantages with this:

* rendering on docs.typo3.org
* getting rid of some formatting (e.g. `<code>` etc. ) and replacing it with simpler formatting would make the phpdoc more readable as text.  Example: [AliasViewHelper](https://github.com/TYPO3/Fluid/blob/master/src/ViewHelpers/AliasViewHelper.php)
* unify and simplify the already existing inconsistencies

If you are generally open to this, I think some remaining details might be better worked out in a concrete example. That is what I would suggest: I (or someone else) can create a PR for a change (changing maybe just one or 2 files for now as WIP) both in TYPO3 core and TYPO3/Fluid.

Additionally, someone should check existing code more thoroughly for used markup and possible edge cases. I just did that:

Results: Used formatting in [TYPO3/Fluid](https://github.com/TYPO3/Fluid/tree/master/src/ViewHelpers)

*  code snippets with `<code>` (actually there is already some inconsistency: currently, `<code>`, indenting **and** indenting with `::` already exist). Example: [InlineViewHelper](https://github.com/TYPO3/Fluid/blob/master/src/ViewHelpers/InlineViewHelper.php), [If ViewHelper](https://github.com/TYPO3/Fluid/blob/master/src/ViewHelpers/IfViewHelper.php)
* headers with `= Examples =` >> use underline
* lists: must add newline before / after e.g. [IfViewHelper](https://github.com/TYPO3/Fluid/blob/7712d383a947333be3291d9e9b1630d44275c563/src/ViewHelpers/IfViewHelper.php#L24)

Used languages in code blocks:

* Fluid 
* inline Fluid
* HTML output 
* plaintext 

All of these can use language XML for syntax highlighting. If there is no language specified (by us in the rendering toolchain) and there is no syntax highlighting, that would also work.

**Comment by NamelessCoder** [comment]
> What I would do is add guidelines to the contribution information in your repo

*Very* good point, that's completely missing and should state something now about target branch (master or 3.0 since they completely diverge) and could easily contain a couple of lines about phpdoc for ViewHelpers.

> If you are generally open to this, I think some remaining details might be better worked out in a concrete example.

I agree - and I agree. We have https://github.com/TYPO3/Fluid/pull/436 open which addresses the markup in phpdoc, but that one contains wide-spread use of `note` etc., cleaning that up would make it acceptable.

* That patch can receive a pull request targeted at @DanielSiepmann's branch which he would be in control of merging.
* Any patches to TYPO3 core can be assigned with me as reviewer and I'll take care of them.

> All of these can use language XML for syntax highlighting.

Completely right and even if they did contain a stray XML tag then that would be nicely highlighted as code inline in the text.

I think we have an acceptable solution for both TYPO3 core and Fluid! Thanks for taking time to find a good compromise.

**Comment by DanielSiepmann** [comment]
I would be happy to receive the PR and merge it :)

**Comment by marble** [comment]
I didn't read the above. Note that there also is a reST directive `.. highlight:: guess` which turns on highlighting for code blocks and simple takes the first language for that the lexer doesn't run into an error. But that may not be what we want. On the other hand, it MAY be possible to tell Pygments which languages to try first. I havent done any investigation on that yet.

**Comment by sypets** [comment]
Having additional special reST directives in the code is something we want to avoid in any case.

If that is added on by the automatic generation toolchain for the VHref, that is ok. I strongly suspect this is what is happening already (either with "guess" or "xml") because it renders fine with syntax hightlighting, e.g. here: 

https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/If.html
See the first code block. That already does it in a way I am suggesting with the `::`. 

Daniel should know better what is happening internally. Like I said above, using "xml" should be fine.

We are not changing anything that will break things. On the contrary. It should work better, than it does now with the automatic rendering. I don't think there is any need to change anything in the automatic VHref generation, not for this change anyway.
