### ISSUE TITLE
Wrong decision in SwitchViewHelper

### ISSUE THREAD

**Issue by dkoether** [TYPO3/Fluid#520]
Hello everyone,

I think there is a bug in fluid found by using the TYPO3 ViewHelper f:switch. Let me explain it with the following example. This is the snippet to reproduce the misbehaviour.

```
<f:switch expression="3-non-slide">
    <f:case value="6">
            CASE 6
        </f:case>
        <f:case value="3">
            CASE 3
        </f:case>
        <f:case value="3-non-slide">
            CASE 3-non-slide
        </f:case>
        <f:case value="2-non-slide">
            CASE 2-non-slide
        </f:case>
        <f:case value="2">
            CASE 2
        </f:case>
        <f:case value="2-with-2-elements">
        CASE 2-with-2-elements
        </f:case>
</f:switch>
```

If I'm not doing something terribly wrong then the result should be "CASE 3-non-slide" but it is "CASE 3" instead.
For simplicity there is no fluid variable in the expression attribute.

This was confirmed by a second developer. First this was a forge ticket => https://forge.typo3.org/issues/91713

Thanks in advance!

**Comment by liayn** [comment]
The code within the f:case does:

```
// non-type-safe comparison by intention
if ($switchExpression == $value) {
```

So what you experience here is actually not a Fluid bug, but a PHP behaviour.

`"3-non-slide" == 3` is `true` in PHP.

**Comment by dkoether** [comment]
Ah, so can we do something about this to avoid the problem or do we have to accept this as the normal behaviour of PHP and stop using values like I did?

**Comment by NamelessCoder** [comment]
> Ah, so can we do something about this to avoid the problem or do we have to accept this as the normal behaviour of PHP and stop using values like I did?

You have multiple options at your disposal:

* Use values of a different nature, e.g. prefix with a string to make weak numerical comparison false.
* Use `f:if` + `f:else` with `if` argument to make an if-then-elseif-else structure, and use `===` in your comparisons.
* Create sections with names where part of the name is the value you want to match, e.g. `<f:section name="Value3">` then render the section with `section="Value{variableWithValue}"` and `optional="1"` and possibly `default="..."` or use tag content of `f:render` to make a default output.

**Comment by dkoether** [comment]
Thank you @liayn and @NamelessCoder !

Your third option is a good solution 👍🏻

**Comment by dkoether** [comment]
For Posterity: The string to number comparison has changed in PHP 8.0 so this behaviour will not occur again.

Comparison:
3 == "3-non-slide" 

Before:
true 

After:
false

See full scenario table here:
https://www.php.net/manual/de/migration80.incompatible.php
