### ISSUE TITLE
[FEATURE] Add "aria" argument to AbstractTagBasedViewHelper

### ISSUE THREAD

**Issue by o-ba** [TYPO3/Fluid#534]
Since accessibility is a very important topic in the web, the Fluid framework should support its developers as much as possible in building user-friendly and accessible applications. A first step is to describing elements with `aria` (Accessible Rich Internet Applications) attributes. Further reading: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA.

To ease the use of these attributes, the same functionality as for the `data` attributes should also be implemented for the `aria` attributes. Especially since there are some limitations for using `additionalAttributes`. See for example: https://forge.typo3.org/issues/93963

**Comment by mbrodala** [comment]
There's already a PR pending in #530 for this ...

**Comment by o-ba** [comment]
Yes, sorry. I just searched for an existing issues, not for existing PRs.

How would you like to proceed, since #535 does not only allow to pass the `aria-` attribute, but also allows to define them with a new VH argument and supports them in `TagBuilder->addAttribute()`. Having a dedicated argument is required, see the TYPO3 forge [issue](https://forge.typo3.org/issues/93963). I furthermore already applied the same test coverage as for the `data-` attribute functionality.

**Comment by mbrodala** [comment]
As discussed I'd vote for including #530 first since it handles a part of the topic. Then #535 can be added on top focussing on the `aria` argument alone.

**Comment by o-ba** [comment]
Yes, fine for me.
