### ISSUE TITLE
Fluid 3: Parameter of Atom does not support variables

### ISSUE THREAD

**Issue by sascha-egerer** [TYPO3/Fluid#540]
If i pass a variable as argument to an Atom the value is always null.

```
    <my:atom name="bar"></my:atom>

    <f:variable name="foo">bar</f:variable>
    <my:atom name="{foo}"></my:atom>
```

The first one works (`{name}` is `bar` in `atom`) but in the second example `{name}` is always null

**Comment by lolli42** [comment]
Hey.
As outlined in https://github.com/TYPO3/Fluid/issues/591, we'll close v3 related issues for now.
I hope this is fine with you, and we may catch up on v3 codebase later again, in case development continues to happen on it.
