### ISSUE TITLE
Fluid 3: Add f:children viewhelper to render Atom childrens

### ISSUE THREAD

**Issue by sascha-egerer** [TYPO3/Fluid#545]
Currently childrens of an Atom are appended to the atom. This is not very intuitive.
I would suggest to add an `<f:children>` Viewhelper which renders the children at a specific place instead of always appending them to the atom.

**Current behavior:**
Atom:
```html
<div class="atom">
</div>
```

Input:
```html
<my:atom>
   my content
</my:atom>
```

Output:
```html
<div class="atom">
</div>
my content
```

**New behavior**

_Without f:children_
Atom:
```html
<div class="atom">
</div>
```

Input:
```html
<my:atom>
   my content
</my:atom>
```

Output (children will not get rendered at all due to missing <f:children>):
```html
<div class="atom">
</div>
```

_With f:children_
Atom:
```html
<div class="atom">
   <f:children />
</div>
```

Input:
```html
<my:atom>
   my content
</my:atom>
```

Output
```html
<div class="atom">
    my content
</div>
```

**Comment by lolli42** [comment]
Hey.
Since this is related to the stalled fluid v3 development, I hope it is ok to close here for now according to the reasoning outlined in https://github.com/TYPO3/Fluid/issues/591.
