### ISSUE TITLE
Fluid 3: Support enumerations for f:parameter

### ISSUE THREAD

**Issue by nmaier95** [TYPO3/Fluid#546]
For better usability/documentation on how a parameter for e.g. an atom template works it'd be great if `f:parameter` would support something like a `oneof` attribute working similar like this:
```
<f:parameter name="buttonType" type="string" oneof="{0: primary, 1: secondary, 2: tertiary}" />
```

Which is very useful if you build your css classes with e.g. BEM syntax and work with modifiers:
```
<div class="a-button a-button--{buttonType}">...</div>
```

**Comment by lolli42** [comment]
Hey.
Since this is related to the stalled fluid v3 development, I hope it is ok to close here for now according to the reasoning outlined in https://github.com/TYPO3/Fluid/issues/591.
