### ISSUE TITLE
f:form.hidden inconsistency for disabled attribute

### ISSUE THREAD

**Issue by aimeos** [TYPO3/Fluid#553]
These tags will all throw an exception:
```
<f:form.hidden name="test" value="1" disabled />
<f:form.hidden name="test" value="1" disabled="disabled" />
```
Exception:
> Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Form\HiddenViewHelper: disabled. Valid arguments are: additionalAttributes, data, aria, name, value, property, class, dir, id, lang, style, title, accesskey, tabindex, onclick

Other f:form.* tags allow `disabled="disabled"` so the behavior is inconsistent .

**Comment by mbrodala** [comment]
There are no form viewhelper in the Fluid library, please open a ticket in the TYPO3 issue tracker instead.
