### ISSUE TITLE
Insert a variable in a CSS context...

### ISSUE THREAD

**Issue by docmcfly** [TYPO3/Fluid#560]
I implement a typo3 extension. Here are rows from my template: 

```
<style type="text/css">
.specialForces {
	background-color: {specialForcesColor};
</style>
<div class="specialForcesColor" > ...</div>
```
It does not work. The specialForcesColor is specified by a flexform. It is possible to modify the css class definition?

Thank for your help 
Clemens

**Comment by mbrodala** [comment]
Please use the TYPO3 support channels for questions like this: https://typo3.org/help

If you end up finding a bug in Fluid, you can report it here.
