### ISSUE TITLE
AliasViewHelper has side effects

### ISSUE THREAD

**Issue by cundd** [TYPO3/Fluid#666]
I just recognized that `<f:alias>` has side effects if one of the alias-names matches an outer variable name.

Example:

```php
<?php

$this->view->assign('seminars', [
    'open'   => ['Seminar 1', 'Seminar 2'],
    'closed' => ['Seminar 3', 'Seminar 4'],
]);
```

```html
<!-- `seminars` contains the nested array -->
<f:alias map="{seminars : seminars.open}">
    <f:render section="list" arguments="{_all}"/>
</f:alias>

<!-- `seminars` is `NULL` because of https://github.com/TYPO3/Fluid/blob/main/src/ViewHelpers/AliasViewHelper.php#L87 -->
<f:alias map="{seminars : seminars.closed}">
    <f:render section="list" arguments="{_all}"/>
</f:alias>
```

The reason is, that the original values are not preserved in [AliasViewHelper.php](https://github.com/TYPO3/Fluid/blob/main/src/ViewHelpers/AliasViewHelper.php) but any value with the mapped key will simply be dropped.

Would it be a viable solution to clone the variable provider in https://github.com/TYPO3/Fluid/blob/main/src/ViewHelpers/AliasViewHelper.php#L80 and reuse the original one after `$renderChildrenClosure()`?

**Comment by cundd** [comment]
The same is true for the `<f:for>` View Helper.

**Comment by masi** [comment]
Odd. I thought the whole idea was to encapsulate the assignments.
