### ISSUE TITLE
[BUG] Array to string conversion warning in AbstractNode

### ISSUE THREAD

**Issue by sbuerk** [TYPO3/Fluid#826]
Note: Created based  on https://forge.typo3.org/issues/102264

Hi,
Exception throws at: /var/www/html/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php line 73
That means:

    {
        if (is_object($value) && !method_exists($value, '__toString')) {
            throw new Parser\Exception('Cannot cast object of type "' . get_class($value) . '" to string.', 1273753083);
        }
        $output = (string)$value;
        return $output;
    }

The line $output = (string)$value; throws it, but the error in mho is in the preceeding if statement: It's asking for object, but not for an array. (Which is the case there).

![Screenshot 2023-10-26 at 14-05-20 TYPO3 Exception](https://github.com/TYPO3/Fluid/assets/1453466/a91e086e-650a-4958-a7b7-f7033abca53f)

**Comment by subnoodle** [comment]
Stefan, that is AWESOME. Thank you!
