### ISSUE TITLE
Latest updates breaks image processing

### ISSUE THREAD

**Issue by cepheiVV** [TYPO3/Fluid#853]
In our TYPO3 v11.5.33 & PHP 8.1.26, the update to version `typo3fluid/fluid` 2.9.3 or version 2.10.2 causes TYPO3 image processing to create large zoomed-in images. We had to lock `typo3fluid/fluid` to version 2.9.2 so TYPO3 would generate the correct images again.

**Comment by sascha-egerer** [comment]
@cepheiVV  Fluid does not process images. Looks like that is related to TYPO3 and it's Fluid ViewHelpers.

**Comment by cepheiVV** [comment]
But it is the only change in our env. The only difference is switching from `typo3fluid/fluid` version 2.9.2 to 2.9.3 which causes image processing to fail. @sascha-egerer

**Comment by sascha-egerer** [comment]
Do you have any details? Can you reproduce the issue somehow in a clean setup?
Weird zoomed in images may have something to do with a missing exif php extension. But this would not explain why a fixed fluid version will fix the issue. 
Is is it really only the fluid version that makes the difference?

**Comment by cepheiVV** [comment]
I'm sure that it was the only change. I tested this in my local ddev and on our webserver.
In both instances, I locked `typo3fluid/fluid` to 2.9.2, removed processed images and reloaded the FE to get the correct images back. I haven't tested this in a fresh installation, only in this one project.
We're using the ViewHelper `f:uri.image` to render the affected images.

**Comment by sascha-egerer** [comment]
But f:uri.image is not a fluid ViewHelper but a ViewHelper of the TYPO3 fluid extension. See https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ImageViewHelper.php

So i'm not sure how this should be related to each other. 

Maybe something has changed with the width and height attributes given to the ViewHelper. Could you please check if you're setting any width or height in Fluid and maybe debug the values with the "new" and "old" Fluid version?

**Comment by cepheiVV** [comment]
You're right. The `height` param has changed.
The height attribute we're setting is `height: '{width / aspectRatio}'`

In version 2.9.2 this resulted in `0` (which is probably wrong?) and in version 2.10.1 I'm getting a value for this calculation:

Version 2.9.2: => `1400 / 0.83 = 0`
Version 2.10.1: => `1400 / 0.83 = 1686.7469879518` (which is correct)

<img width="291" alt="Screenshot 2023-12-20 at 00 28 36" src="https://github.com/TYPO3/Fluid/assets/2963482/903ad9c8-26e1-4e77-ac12-eccb878b8579">

<img width="270" alt="Screenshot 2023-12-20 at 00 30 30" src="https://github.com/TYPO3/Fluid/assets/2963482/4f50b627-0e38-4eb4-9d90-6311b24d6a4a">

So there's probably been a math fix in `typo3fluid/fluid` and due to the now correct value, our setup breaks.

@sascha-egerer Thanks for walking me thru this. I'm clong this issue.

**Comment by sascha-egerer** [comment]
👍

**Comment by s2b** [comment]
> So there's probably been a math fix in `typo3fluid/fluid` and due to the now correct value, our setup breaks.

Just wanted to confirm this. https://github.com/TYPO3/Fluid/commit/16888df70dcaf9da9bf1e9b6da0a8ab74505963c fixes divisions of values smaller than 1. We debated the change and decided that it would classify as a bugfix.
