### ISSUE TITLE
PHP Warning: Array to string conversion in TagBuilder.php line 200

### ISSUE THREAD

**Issue by liayn** [TYPO3/Fluid#857]
Function parameter `$attributeValue` is allowed to be an array.
Therefore the straight conversion to string raises a warning in PHP 8.2.

**Comment by liayn** [comment]
The usage seems to stem from an invalid Viewhelper implementation, still this case should be covered.

**Comment by s2b** [comment]
The method seems to only support arrays if the attribute name is either data or aria. So I would suggest to throw an exception if an array is used for other attribute names.

In general, I think that this is bad API design, however I would argue that it should stay consistent to the existing API at the moment to not be breaking.

If your error occurred in a core ViewHelper, this would be good to know to be able to fix it there as well.

**Comment by s2b** [comment]
@liayn Can you check if the PR fixes your problem?

**Comment by liayn** [comment]
Thanks, will continue in the PR
