### ISSUE TITLE
Fluid Template Variable Parsing Error with Spaces around Operators

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3/Fluid#895]
From: https://forge.typo3.org/issues/104363

h2. Steps to Reproduce:

# Use the following Fluid template code:
<pre><code class="html">
testVar: {testVar} <br/>
A: {testVar - 1} <br/>
B: {testVar - 1 } <br/>
C: {testVar-1} <br/>
D: {testVar + 1} <br/>
E: {testVar + 1 } <br/>
F: {testVar+1} <br/>
</code></pre>
# Set testVar to any integer, e.g., 2.

h3. Expected Output:

<pre><code>testVar: 2
A: 1
B: 1
C: 1
D: 3
E: 3
F: 3
</code></pre>

h3. Actual Output:

<pre><code>testVar: 2
A: 1
B: {testVar - 1 }
C:
D: 3
E: {testVar + 1 }
F: 3
</code></pre>

h2. Analysis:

* The expression {testVar - 1} and {testVar + 1} are parsed correctly when there are spaces around the operator.
* {testVar - 1 } and {testVar + 1 } result in no evaluation and return the expression as a string.
* {testVar+1} without space is parsed and evaluated correctly.
* {testVar-1} without space is not parsed and evaluated correctly.

**Comment by s2b** [comment]
Case C isn't and won't be supported because `testVar-1` is treated as a variable identifier. This is especially useful for array keys properties:

`{myVar.my-array-key.test}`

The leading/trailing whitespace are addressed with the attached PR.
