### ISSUE TITLE
Consider throwing exception if namespace uses https

### ISSUE THREAD

**Issue by s2b** [TYPO3/Fluid#910]
It should be considered if it makes sense to throw an exception if a Fluid namespace is registered with `https://typo3.org/ns/` instead of `http://typo3.org/ns/`. This would be a breaking change.

**Comment by liayn** [comment]
Related #385

**Comment by mbrodala** [comment]
A few more options:
- Change to `typo3.org/ns/` (thus drop the "scheme" altogether)
- `org.typo3.ns` to prevent further confusion altogether

**Comment by lolli42** [comment]
@mbrodala This would be heavily breaking for everyone. I don't think we should do this now.
