### ISSUE TITLE
Avoid output of deprecations?

### ISSUE THREAD

**Issue by s2b** [TYPO3/Fluid#984]
Other widespread PHP libraries seem to use the silencing operator `@` when triggering exceptions. We should probably do the same in Fluid v4. We should check how this affects TYPO3's deprecation logs and test suite.

Related links:

* https://docs.phpunit.de/en/10.5/error-handling.html
* https://symfony.com/doc/current/components/phpunit_bridge.html
* https://stackoverflow.com/questions/41545682/what-is-the-purpose-of-silence-operator-at-sign-before-trigger-error

**Comment by lolli42** [comment]
core does this: https://github.com/TYPO3/typo3/commit/8140ec47928543e2c28c1974f77852a361b26246
the code was moved around a bit over time, but it's still same strategy: log deprecations, even if it has the STFU operator.

**Comment by s2b** [comment]
I just tested this with phpunit's default error handler: The STFU operator in fact is ignored by phpunit. So I would argue to only add the operator to deprecations that are added _after_ a major release and to leave those for Fluid v4 without the operator.

What do you think?
